### ISSUE TITLE
Disengage single-app mode before mandatory update, reengage after.

### ISSUE THREAD

**Issue by jgarth** [bitstadium/HockeySDK-iOS#111]
Hey,

I'm distributing enterprise builds with HockeyApp. Great Stuff so far. However, on the client's devices, the App is locked in single-app mode, which prevents itms-service from doing the actual update. 

iOS 7 provides a public API to request entering single-app mode and leaving it – [UIAccessibilityRequestGuidedAccessSession()](https://developer.apple.com/library/ios/documentation/uikit/reference/UIKitFunctionReference/Reference/reference.html#//apple_ref/c/func/UIAccessibilityRequestGuidedAccessSession) – so it would be possible to leave single-app mode before the update and re-enter it afterwards. I would really appreciate support for this and I see two ways to accomplish said behavior:

- Get two delegate messages on my BITUpdateManagerDelegate: -willInstallUpdate and -didInstallUpdate, so I can do the leaving/entering single-app mode myself, 
or
- Have native support for this. Hockey could possibly check for guided access via UIAccessibilityIsGuidedAccessEnabled() and try to terminate single-app mode on its own?

Thanks for considering.

**Comment by anlinde** [comment]
This is now part of release 3.6.4.
