### ISSUE TITLE
Problem with 'Build Active architecture only' flag set to NO for debug configuration

### ISSUE THREAD

**Issue by scheinem** [bitstadium/HockeySDK-iOS#114]
Hello,

in commit d81e7381f53ed3817480b625944309eb5b9372aa you changed the 'Build active architecture only' flag from `NO` to `YES`(I think because it's recommended by Xcode's 'Upgrade scheme to recommend settings' feature). But this option causes problems for me when trying to run my application in simulator (Xcode complains `BITHockeyManager` isn't found for architecture i386 in libHockeySDK.a). Switching 'Build active architecture only' back to `YES` makes it working again.

Is there any possibility that you revert this change in the next release or will this be a steady one?

Thanks in advance!

**Comment by anlinde** [comment]
I don't see anything we have to change here. The next SDK update will use binary distribution by default via CocoaPods too. There will be an option to use source integration, but even with that, everything works just fine over here. Without being able to reproduce any of the issues, I can't possible change the build system.

Closing this for now.
