### ISSUE TITLE
BITHOCKEY_VERSION macro redefined warning

### ISSUE THREAD

**Issue by x2on** [bitstadium/HockeySDK-iOS#116]
Since 3.5.7 i get the a lot of warnings with Xcode 6:

`'BITHOCKEY_VERSION' macro redefined`

Any idea how to solve this?

**Comment by dreese** [comment]
Somehow, my project got into this state too. Removing the definitions from `GCC_PREPROCESSOR_DEFINITIONS` fixed it for me too.
