### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by oleg-ivaniv** [bitstadium/HockeySDK-iOS#128]
Hi,
There is a problem with Spanish localization
![img_0070](https://cloud.githubusercontent.com/assets/2520289/6017033/6377d4c2-ab92-11e4-85c9-da415f595314.png)
Would be nice if this will be fixed (I also will try to fix it).

Thank you.

**Comment by anlinde** [comment]
Hi,

could you provide some more details on this:

1. Which Xcode version are you using?
2. This iOS version is this tested with?
3. Is this using the iPhone simulator or device?
4. Which device type is this?
5. Are you using the binary distribution of our SDK?
6. Which version of our SDK are you using?

Thanks,
Andreas

**Comment by anlinde** [comment]
This is what we get with iOS 8.1 on iPhone 6 simulator:

![ios 8 1 12b411 2015-02-03 13-11-18](https://cloud.githubusercontent.com/assets/10196267/6019954/51f69b34-aba6-11e4-85ad-0ab89b584b53.png)

**Comment by oleg-ivaniv** [comment]
Hi,
I can see this issue on simulator and real device.
Which Xcode version are you using? - latest one
This iOS version is this tested with? - 8.1.2. (iPhone 6+) and 8.1.3.(iPhone 5s)
Is this using the iPhone simulator or device? - both
Which device type is this? - iPhone 6+
Are you using the binary distribution of our SDK? - pod
Which version of our SDK are you using? - latest one (3.6.2.)

**Comment by anlinde** [comment]
We sadly can't reproduce this, so I have no idea what is causing this.

Can you reproduce the issue using the binary distribution instead of including the SDK using CocoaPods? http://hockeyapp.net/releases/

**Comment by oleg-ivaniv** [comment]
Yes, I tried binary distribution instead of including the SDK using CocoaPods and I have the same result.

**Comment by anlinde** [comment]
Would it be possible to create a sample app which shows this issue for you and contact us via support at hockeyapp dot net?

**Comment by oleg-ivaniv** [comment]
Hi,
Contacted here http://support.hockeyapp.net/discussions/problems/35514-localization-issue

**Comment by TheRealKerni** [comment]
We need a sample app that reproduces this issue, since we can't reproduce it here.

**Comment by oleg-ivaniv** [comment]
I tried to create simple app, but there everything works fine.
Obviously, this is a bug from my side. 
Sorry for that.
