### ISSUE TITLE
Several warnings with Xcode 6.3 beta

### ISSUE THREAD

**Issue by sticksen** [bitstadium/HockeySDK-iOS#130]
![screen shot 2015-02-10 at 12 21 46](https://cloud.githubusercontent.com/assets/2657113/6126307/86d335be-b11f-11e4-9c27-afb92ea583f6.png)
![screen shot 2015-02-10 at 12 23 48](https://cloud.githubusercontent.com/assets/2657113/6126325/b3df2162-b11f-11e4-8d45-ef301f5939b4.png)

**Comment by anlinde** [comment]
Hi,

these warnings are fixed on HEAD of the develop branch.

Thanks,
Andreas
