### ISSUE TITLE
Pod fails to copy its resources

### ISSUE THREAD

**Issue by akashivskyy** [bitstadium/HockeySDK-iOS#131]
The HockeySDK-iOS pod fails to copy its `HockeySDKResources.bundle`:

```none
Run custom shell script 'Copy Pods Resources'

/bin/sh -c /Path/To/Build/Script-D75B26C7F4A330D83F7AC697.sh

... other files ...

/Path/To/Pods/${BUILT_PRODUCTS_DIR}/HockeySDKResources.bundle
building file list ... rsync: link_stat "/Path/ToPods/${BUILT_PRODUCTS_DIR}/HockeySDKResources.bundle" failed: No such file or directory (2)

done

... other files ...

sent 70204 bytes  received 668 bytes  47248.00 bytes/sec
total size is 67920  speedup is 0.96
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

The actual build and project's pods directory paths have been shortened to `/Path/To/Build/` and `/Path/To/Pods/` accordingly.

---

- **CocoaPods version:** 0.35.0
- **HockeySDK-iOS version:** 3.6.2

**Comment by anlinde** [comment]
This is a bug in CocoaPods 0.36 Beta 2, see here: https://github.com/CocoaPods/CocoaPods/issues/3082

We recommend to either use a stable version of CocoaPods or the binary distribution of our SDK.

**Comment by akashivskyy** [comment]
I'm using CocoaPods 0.35, as I wrote above. :stuck_out_tongue:

**Comment by anlinde** [comment]
This doesn't happen with CocoaPods 0.35 in any of our tests and it is a documented bug in that specific beta version. Did you run `pod install` again?

**Comment by akashivskyy** [comment]
Alright, I had a local Bundler's CocoaPods installation, which took precedence over the system's installation.

```rb
gem 'cocoapods', '~> 0.36.0.beta.2'
```

Sorry for trouble!
