### ISSUE TITLE
Inconsistency in log/attachment delegate callbacks and last session details setup

### ISSUE THREAD

**Issue by dippnsk** [bitstadium/HockeySDK-iOS#136]
Hi!

I have a case where I need to have last session crash details in applicationLogForCrashManager delegate. But in current implementation this is not possible, because order of calling callbacks not allows to do that:
```
- (void) handleCrashReport {
...
// Here we get applicationLogForCrashManager call
[self storeMetaDataForCrashReportFilename:cacheFilename];

NSString *incidentIdentifier = @"???";
if (report.uuidRef != NULL) {
    incidentIdentifier = (NSString *) CFBridgingRelease(CFUUIDCreateString(NULL, report.uuidRef));
}
        
NSString *reporterKey = bit_appAnonID() ?: @"";

// Here lastSessionCrashDetails is set
_lastSessionCrashDetails = [[BITCrashDetails alloc] initWithIncidentIdentifier:incidentIdentifier ...
...
````
I think, SDK must first set crash details and then request for additional content for this crash. In createCrashReportForAppKill I see exactly this behavior but in handleCrashReport for some reason order is different.

**Comment by anlinde** [comment]
Hi,

I just updated this in the develop branch so it will be part of the next release.

Best,
Andreas

**Comment by dippnsk** [comment]
Wow, that was fast! :) Thanks! Will wait for release.

**Comment by anlinde** [comment]
The latest 3.6.4 release contains the fix.
