### ISSUE TITLE
HockeySDK(3.6.2) CocoaPod(0.35.0 and 0.36.0) validation Warning

### ISSUE THREAD

**Issue by levieggert** [bitstadium/HockeySDK-iOS#137]
Hey guys, hoping you can help me figure out this strange issue.  All of a sudden I'm getting a warning when I try to validate my pod spec. 

The warning is coming from BITUpdateManager.m:746.

- WARN  | HockeySDK/Classes/BITUpdateManager.m:746:30: warning: code will never be executed [-Wunreachable-code]

I see in v 3.6.2 you had a fix for that warning by including the #else.

However, my local 3.6.2 version I still see #endif which would cause the unreachable code.  So for some reason it's as if 3.6.2 is still pulling an older BITUpdateManager file.

Everything was working fine until I updated to CocoaPods 0.36.0.  A couple days ago I was validating my pod spec with HockeySDK 3.6.2 and passing validation.  I went back to CocoaPods 0.35.0 and the warning is still there.

My Local 3.6.2 version.

![screen shot 2015-03-14 at 2 29 44 pm](https://cloud.githubusercontent.com/assets/3237018/6653625/b8dd826c-ca56-11e4-9923-2d8df3b28041.png)

What I see on Github.

![screen shot 2015-03-14 at 2 31 33 pm](https://cloud.githubusercontent.com/assets/3237018/6653629/e190c34a-ca56-11e4-9d7c-7c35d4b71890.png)

**Comment by levieggert** [comment]
Hey just realized I have to uninstall 0.36.0 to completely roll back.

Saw that in some related issues others were having with 0.36.0.

I am now able to validate my spec.  I'll stay on 0.35.0 for now.

Thanks!

**Comment by anlinde** [comment]
This is already fixed in the develop branch.
