### ISSUE TITLE
Other typos

### ISSUE THREAD

**Issue by tewha** [bitstadium/HockeySDK-iOS#139]
When looking for easily-corrected typos, I found a few that didn't look so easy. These are not part of my pull request.

Public API:

	- timeintervalCrashInLastSessionOccured
	+ timeintervalCrashInLastSessionOccurred

Other API, may be exposed:

	- BITFeedbackListViewCellPresentatationStyle
	+ BITFeedbackListViewCellPresentationStyle

	- BITFeedbackListViewCellPresentatationStyleDefault
	+ BITFeedbackListViewCellPresentationStyleDefault

	- BITFeedbackListViewCellPresentatationStyleOS7
	+ BITFeedbackListViewCellPresentationStyleOS7

Internationalization:

	- HockeyFeedbackListButonWriteFeedback
	+ HockeyFeedbackListButtonWriteFeedback

	- HockeyFeedbackListButonWriteResponse
	+ HockeyFeedbackListButtonWriteResponse

	- HockeyFeedbackListButonUserDataWithName
	+ HockeyFeedbackListButtonUserDataWithName

	- HockeyFeedbackListButonUserDataWithEmail
	+ HockeyFeedbackListButtonUserDataWithEmail

	- HockeyFeedbackListButonUserDataSetName
	+ HockeyFeedbackListButtonUserDataSetName

	- HockeyFeedbackListButonUserDataSetEmail
	+ HockeyFeedbackListButtonUserDataSetEmail

	- HockeyFeedbackListButonDeleteAllMessages
	+ HockeyFeedbackListButtonDeleteAllMessages

Other:

	- feedbackActiviy.png
	+ feedbackActivity.png

	- HockeyFeedbackuserID
	+ HockeyFeedbackUserID

**Comment by TheRealKerni** [comment]
Thanks Steven. Oh. My. Goodness. What did I do.

I decided to take all of these up except `HockeyFeedbackuserID`, since that would break existing apps and can't be easily fixed in code. 

See https://github.com/bitstadium/HockeySDK-iOS/commit/7eef1c4075dd7d180c7ed9a45162133704c46f89

**Comment by tewha** [comment]
Sounds good! `HockeyFeedbackuserID` is not really a spelling error, anyway, it's just weird and chokes spell checkers even if they handle camel case well.
