### ISSUE TITLE
Can't use HockeySDK with Rollbar SDK

### ISSUE THREAD

**Issue by vGubriienko** [bitstadium/HockeySDK-iOS#145]
I can't install HockeySDK via pods with next error:
`[!] The 'Pods-*********' target has frameworks with conflicting names: CrashReporter.`
The `CrashReporter` framework used in the Rollbar SDK.
Any thoughts how I can use them both (with disabled crash reporter in the Rollbar)

**Comment by TheRealKerni** [comment]
You can use our SDK via the binary distribution. When building from source and two SDKs are including a framework with the same name, you will always have this issue.

**Comment by vGubriienko** [comment]
Thanks!
