### ISSUE TITLE
Attached images bugs

### ISSUE THREAD

**Issue by oleg-ivaniv** [bitstadium/HockeySDK-iOS#148]
Hi,
During using HockeySDK-iOS I found some bugs. 
Steps to reproduce:
1. Attach to feedback 2 or 3 images.
2. Select any image and press "Edit Image"

Expected result: 
- selected image should be opened for editing

Actual result:
- some another image opened (not selected one)

Another issue:
Steps to reproduce:
1. Attach to feedback 2 or 3 images.
2. Select any image and press "Delete Image"

Expected result:
- selected image should be deleted;

Actual result:
- random image will be deleted or sometimes app crash.

Environment info:
- iPhone 6+, iOS 8.2
- HockeySDK 3.6.2

Test project that demonstrates issues:
https://github.com/oleg-ivaniv/HockeySDKDemo

**Comment by anlinde** [comment]
Hi Oleg,

thanks for reporting this. We already fixed this in the develop branch and will soon release an update with these fixes included.

Best,
Andreas

**Comment by oleg-ivaniv** [comment]
Thank you for prompt answer!
Looks like I can close this issue.

Have a nice day!
