### ISSUE TITLE
Support for Crash Only SDK with CocoaPods

### ISSUE THREAD

**Issue by johntmcintosh** [bitstadium/HockeySDK-iOS#152]
Hi - 

I'm in the process of setting up crash reporting in a watch extension, and have been using CocoaPods for managing dependencies. Based on the [iOS Integration Guide](http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/hockeyapp-for-ios#crash-reporting-only-sdk) I'm able to link the precompiled Crash Only version of the framework. I would like to be able to continue using CocoaPods, but the current podspec in the repo does not support linking the crash only framework.

It seems like a good solution here would be to support [subspecs](https://guides.cocoapods.org/syntax/podspec.html#group_subspecs) in the podspec, so that users could link whichever version of the framework they prefer. 

I made an attempt at trying this (full details below), but ran into some linker errors which seem to indicate that the crash only version of the framework may be built from different versions of the source files than those in the public repo. Is that the case?

I'd be happy to submit a pull request with an updated version of the podspec that would make adding crash support to extensions easier for everyone, but I think we'd need to get some additional source files added to the repo before I could.

Is there anything I'm overlooking, or do you have any other suggestions of how to go about updating the podspec to support the crash only configuration for iOS 8 extensions?

--

Here's what I tried... I created the following modified version of the podspec which defines two subspecs: `Full` and `CrashOnly`. It sets `Full` as the default spec, so that existing pod users would need to make no change to maintain their existing behavior.

Also, and I'm guessing a little here, to choose the list of source files to include in the `CrashOnly` subspec, I copied the list of public header files in the framework, and specified to use any .h and .m that matches those names. 

Here's the updated spec:

```
Pod::Spec.new do |s|
  s.name              = 'HockeySDK'
  s.version           = '3.6.4'

  s.summary           = 'Collect live crash reports, get feedback from your users, distribute your betas, and analyze your test coverage with HockeyApp.'
  s.description       = <<-DESC
                        HockeyApp is a service to distribute beta apps, collect crash reports and
                        communicate with your app's users.
                        
                        It improves the testing process dramatically and can be used for both beta
                        and App Store builds.
                        DESC

  s.homepage          = 'http://hockeyapp.net/'
  s.documentation_url = 'http://hockeyapp.net/help/sdk/ios/3.6.4/'

  s.license           = 'MIT'
  s.author            = { 'Andreas Linde' => 'mail@andreaslinde.de', 'Thomas Dohmke' => "thomas@dohmke.de" }
  s.source            = { :git => 'https://github.com/bitstadium/HockeySDK-iOS.git', :tag => s.version.to_s }

  s.platform          = :ios, '6.0'
  s.requires_arc      = true
  
  s.frameworks              = 'AssetsLibrary', 'CoreText', 'CoreGraphics', 'MobileCoreServices', 'QuartzCore', 'QuickLook', 'Security', 'SystemConfiguration', 'UIKit'
  s.ios.vendored_frameworks = 'Vendor/CrashReporter.framework'
  s.xcconfig                = {'GCC_PREPROCESSOR_DEFINITIONS' => %{$(inherited) BITHOCKEY_VERSION="@\\"#{s.version}\\"" BITHOCKEY_C_VERSION="\\"#{s.version}\\"" BITHOCKEY_BUILD="@\\"38\\"" BITHOCKEY_C_BUILD="\\"38\\""} }

  s.default_subspec = 'Full'

  s.subspec 'Full' do |ss|
    ss.source_files = 'Classes'
    ss.private_header_files  = 'Classes/*Private.h'
    ss.resource_bundle         = { 'HockeySDKResources' => ['Resources/*.png', 'Resources/*.lproj'] }
    ss.preserve_paths          = 'Resources', 'Support'
    ss.ios.vendored_frameworks = 'Vendor/CrashReporter.framework'
  end

  s.subspec 'CrashOnly' do |ss|
    ss.source_files = ["Classes/BITCrashAttachment.{h,m}", "Classes/BITCrashDetails.{h,m}", "Classes/BITCrashManager.{h,m}", "Classes/BITCrashManagerDelegate.{h,m}", "Classes/BITCrashMetaData.{h,m}", "Classes/BITHockeyAttachment.{h,m}", "Classes/BITHockeyBaseManager.{h,m}", "Classes/BITHockeyBaseViewController.{h,m}", "Classes/BITHockeyManager.{h,m}", "Classes/BITHockeyManagerDelegate.{h,m}", "Classes/HockeySDK.{h,m}", "Classes/HockeySDKFeatureConfig.{h,m}"]
    ss.ios.vendored_frameworks = 'Vendor/CrashReporter.framework'
  end

end
```

After updating my pods with this spec, I get a few compilation errors in `BITCrashManager.m` when compiling for the watch extension. For exmample, the errors include:

```
.../Pods/HockeySDK/Classes/BITCrashManager.m:924:23: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

.../Pods/HockeySDK/Classes/BITCrashManager.m:977:55: 'initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:' is unavailable: not available on iOS (App Extension) - Use UIAlertController instead.

.../Pods/HockeySDK/Classes/BITCrashManager.m:1113:23: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```

However, running `nm` for a symbol dump on the pre-compiled crash only version of the framework indicates that `BITCrashManager` is part of that library. So, it seems that there must be a different version of the crash manager class that's being used in the crash only framework than the standard version.

Thanks!

John

**Comment by anlinde** [comment]
Hi,

we'll provide an updated Podspec which uses the binary distributions with the next minor update. Until then, you should modify the file `HockeySDKFeatureConfig.h` and de-activate the features you don't want to include in your build. The CrashOnly version e.g. is build with all features but Crash Reporting de-activated.

Regarding your errors: The code checks at runtime if it runs as being part of an extension or not. So you shouldn't activate `APPLICATION_EXTENSION_API_ONLY` for your Pods or you have to modify the source further.

Best,
Andreas

**Comment by johntmcintosh** [comment]
Thanks, Andreas! In the meantime, I've added a post-install script to my podfile to make the changes you suggested.

```
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        
        # Configure hockey for crash reporting only for the watch extension
        if target.name == "Pods-WatchExtension" || target.name == "Pods-WatchExtension-HockeySDK"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'HOCKEYSDK_FEATURE_FEEDBACK=0', 'HOCKEYSDK_FEATURE_STORE_UPDATES=0', 'HOCKEYSDK_FEATURE_AUTHENTICATOR=0', 'HOCKEYSDK_FEATURE_UPDATES=0']
            end
        end

        # Disable extension API safety checks for HockeyApp in the watch extension
        if target.name == "Pods-WatchExtension-HockeySDK"
            target.build_configurations.each do |config|
                config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = false
            end
        end
        
    end    
end
```

**Comment by anlinde** [comment]
Hi,

the latest podspec with binary distribution supports this settings. We had to remove those options from the new `HockeySDK-Source` podspec again, because we couldn't make it work in all scenarions (static lib, dynamic framework, as dependency etc.).

We'll look into that again with the next major SDK update.

Thanks
Andreas
