### ISSUE TITLE
Crash alert has title "This app Unexpectedly Quit"

### ISSUE THREAD

**Issue by mackuba** [bitstadium/HockeySDK-iOS#163]
The capitalization looks kind of funny there, so I checked where that's coming from. It looks like you're trying to detect the app name and falling back to "This app", but you only take `CFBundleDisplayName` into account. I don't have a `CFBundleDisplayName`, I only have a `CFBundleName`. I'm not 100% sure, but from what I found, `CFBundleDisplayName` isn't required if you have `CFBundleName` (http://stackoverflow.com/a/3465924/78255) - so it would be nice to check both of these keys.

**Comment by anlinde** [comment]
This is now added in the develop branch and will be part of the next update. Thanks for the hint!

The commit is here: https://github.com/bitstadium/HockeySDK-iOS/commit/94537a41327e9b4ae72eee378a5808598f784dd2
