### ISSUE TITLE
Build warnings: Input PNG does not have an 8 bit input depth.

### ISSUE THREAD

**Issue by rggjan** [bitstadium/HockeySDK-iOS#172]
When building with XCode and the newes HockeySDK (3.6.4) I get the following error four times:

```
CopyPNGFile /Users/enterprise/Library/Developer/Xcode/DerivedData/3DAround-gpcjfnwnuxyhslaymecfnlzumgbs/Build/Intermediates/ArchiveIntermediates/3DAround/IntermediateBuildFilesPath/UninstalledProducts/HockeySDKResources.bundle/Blur.png HockeySDK/Resources/Blur.png
cd /Users/enterprise/jenkinsSlaveWorkspace/nxtbgthng_0/Pods
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin"
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/copypng -compress /Users/enterprise/jenkinsSlaveWorkspace/nxtbgthng_0/Pods/HockeySDK/Resources/Blur.png /Users/enterprise/Library/Developer/Xcode/DerivedData/3DAround-gpcjfnwnuxyhslaymecfnlzumgbs/Build/Intermediates/ArchiveIntermediates/3DAround/IntermediateBuildFilesPath/UninstalledProducts/HockeySDKResources.bundle/Blur.png
libpng warning: Warning: Input PNG does not have an 8 bit input depth. Please convert your PNG to 8-bit for optimal performance on iPhone OS.
```

This is detected by our jenkins build system and makes the build yellow.

It didn't happen for version 3.6.2, and I assume it was introduced in ``[UPDATE] Reduced file size of images in HockeySDKResources.bundle by 63%`` (see http://hockeyapp.net/help/sdk/ios/3.6.4/docs/docs/Changelog.html)

**Comment by anlinde** [comment]
Can you provide a demo project? Since we can't reproduce this. Also, with Xcode version are you using?

**Comment by rggjan** [comment]
Here is a test project (rename to zip to extract): ![test_project.zip](https://cloud.githubusercontent.com/assets/128554/8278195/c52d707e-18c9-11e5-9ee5-9d57de6ae3fa.jpg)

Its an empty xcode example project with only the hockey sdk as a podfile.

Here is the output of

pod install && xcodebuild -configuration Release -workspace Test.xcworkspace -scheme Test archive -parallelizeTargets > out.txt

![out.txt](https://cloud.githubusercontent.com/assets/128554/8278222/06671c0c-18ca-11e5-9bf8-3c4706939e70.jpg)

(Again, just rename to txt, I can only upload images here...)

**Comment by anlinde** [comment]
Thanks, but these links don't work. How about creating a repo for this instead?

**Comment by rggjan** [comment]
Thanks for having a look at it :)

Links work for me... just right click, save as, and rename to zip / txt.

If its really not working, I can create a new repository for it anyway, though...

**Comment by anlinde** [comment]
The links in your post do not work, check yourself here: https://github.com/bitstadium/HockeySDK-iOS/issues/172

Anyway, I was able to reproduce and fix the issue here: https://github.com/bitstadium/HockeySDK-iOS/commit/5305474388a9752749b450bcfc815ad482be8b91

Thanks for letting us know about this!

**Comment by rggjan** [comment]
Sorry for the links then, it still works fine for me...

But great that you managed to fix the issue, thanks a lot :D
