### ISSUE TITLE
Error HockeySDK 3.7.0: Framework not found CrashReporter

### ISSUE THREAD

**Issue by rggjan** [bitstadium/HockeySDK-iOS#177]
After updating to HockeySDK 3.7.0 I get the following error in my project during linking:

    ld: framework not found CrashReporter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

My Podfile:

    pod 'HockeySDK'

My Podfile.spec:

    PODS:
      - HockeySDK (3.7.0):
      - HockeySDK/AllFeaturesLib (= 3.7.0)
      - HockeySDK/AllFeaturesLib (3.7.0)

**Comment by anlinde** [comment]
Hi,

the `CrashReporter` framework is not referenced and required any longer. Looks like CocoaPods didn't remove that dependency when updating it in your case. If you can't find the reference and remove it manually, I suggest to remove the Pod completely and add it again from scratch.

Best,
Andreas

**Comment by rggjan** [comment]
That worked, thanks for the help!
