### ISSUE TITLE
Missing translation texts

### ISSUE THREAD

**Issue by x2on** [bitstadium/HockeySDK-iOS#179]
With the release 3.7.0 we only get placeholder texts in the HockeyUI.

So if a update is available there is the following text:
`UpdateAvailable`
`UpdateAlertTextWithAppVersion`
and so on...

**Comment by anlinde** [comment]
Make sure the `HockeySDKResources.bundle` is added to your app. How did you integrate the SDK?

**Comment by x2on** [comment]
`pod 'HockeySDK', '3.7.0'`

**Comment by x2on** [comment]
The `HockeySDKResources.bundle` is then missing in the Pods project :(

**Comment by anlinde** [comment]
Please completely remove the pod and then add it again. That should fix it.

The pod is inside of the framework and definitely is there.

**Comment by x2on** [comment]
Hm i will try - not so easy during a CI build...

**Comment by anlinde** [comment]
We highly recommend not to do `pod install` on CI but check in your pods.

**Comment by x2on** [comment]
Other discussion - but we will not do this :) 
We just checking the `Podfile` and the `Podfile.lock`
Nice article: http://www.jpsim.com/cocoapods-tips-tricks/

**Comment by x2on** [comment]
Just testet it on my Mac - No bundle available in the Pods project after deleting the whole `Pods` folder and run `pod update`
![screen-hockey](https://cloud.githubusercontent.com/assets/195724/8352078/c279c1be-1b32-11e5-8ebe-602d9ecf3bc4.png)

**Comment by anlinde** [comment]
It is not shown in there, but under `Pods`, `Products`.
![sdktest xcodeproj 2015-06-25 12-13-10](https://cloud.githubusercontent.com/assets/10196267/8352201/8dc367e4-1b33-11e5-91a6-b2dd274c7d83.png)

And also part of the app after build:
![sdktest 2015-06-25 12-13-27](https://cloud.githubusercontent.com/assets/10196267/8352203/9cf3c236-1b33-11e5-9395-044a3d65184e.png)

**Comment by x2on** [comment]
Ah i missed that, just thought that is a "normal" resource bundle for the pod.
In the `Name.app` file the bundle is available, but doesn't contain any files

**Comment by anlinde** [comment]
We are trying to reproduce this and find the cause. It is likely a bug in CocoaPods. Are you using `use_frameworks!` ?

**Comment by x2on** [comment]
No we are targeting iOS 7

**Comment by anlinde** [comment]
We are trying to compile of issues that is caused by CocoaPods (so it seems) during update. But until that is fixed we only have the following options:

1. Don't use CocoaPods for our SDK and directly integrate the binary (it only takes a very few steps): http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/hockeyapp-for-ios
2. Try the `HockeySDK-Source` pod instead (doesn't work yet with frameworks, but not relevant for you)
3. Stay on 3.6.4 for now.

**Comment by anlinde** [comment]
We found the issue and it was actually a bug in the podspec. Shame on me.

The fixes have been merged and you should now be able to update the podspec to 3.7.0 without any more issues.

**Comment by anlinde** [comment]
The updated version 3.7.1 should work now for real.

Sorry for the trouble.

**Comment by x2on** [comment]
Thanks with 3.7.1 it works now again!
