### ISSUE TITLE
How to access info from the crash manager delegate

### ISSUE THREAD

**Issue by lauracpierre** [bitstadium/HockeySDK-iOS#180]
Hi, 

I've implemented the delegate methods to get more details about the user when I get a crash report. However I don't understand where in HockeyApp I can have access to this information. 
Also because HockeyApp won't start in debug, it's hard to see if these methods are being called. 

Here is my config: 

```
var hockey = BITHockeyManager.sharedHockeyManager()
hockey.configureWithIdentifier("MY_API_KEY")
hockey.crashManager.crashManagerStatus = .AutoSend
hockey.delegate = self
hockey.startManager()
```

and then I have the following methods: 
```
func userEmailForHockeyManager(hockeyManager: BITHockeyManager!, componentManager: BITHockeyBaseManager!) -> String! {
       // returning the correct email
}
    
func userIDForHockeyManager(hockeyManager: BITHockeyManager!, componentManager: BITHockeyBaseManager!) -> String! {
       // returning the correct ID
}
    
func userNameForHockeyManager(hockeyManager: BITHockeyManager!, componentManager: BITHockeyBaseManager!) -> String! {
       // returning the correct name
}
```

Where can I access these details?

Thank you!

**Comment by anlinde** [comment]
You can test this in Xcode yourself:

1. Run the app without the debugger and let it crash
2. Now start the app with the debugger attached and your breakpoints will work

Crashes are always send on the next startup, that's also when the delegates are called. We can not invoke the delegates at crash time since that can cause way more harm than good (async-safety).

**Comment by lauracpierre** [comment]
Ok thanks for the tip!

That being said where can I see this information on the hockey app website  or hockey app application OS X app?

--
Pierre Laurac

**Comment by anlinde** [comment]
In the "Meta" tab of each crash instance. So select the crash group, then the "Crash Logs" tab, then a crash instance from the list and then the "Meta" tab below.

**Comment by lauracpierre** [comment]
Cool this works fine then! I looked mainly on the Mac App which doesn't seem to exist but that's fine. 

Thanks for the quick response and the good work on the app and frameworks!

Pierre
