### ISSUE TITLE
Crash after the app has been installed

### ISSUE THREAD

**Issue by oleg-ivaniv** [bitstadium/HockeySDK-iOS#181]
Hi,

Crash preconditions: send one or more feedback than delete app from device and install this app again; list of sended feedbacks must not be downloaded, so try steps directly after app has been installed.

Steps to reproduce:
1. Go to Feedback in portrait mode
2. Rotate device to landscape mode

After this is 2-5 sec app will crash.

Crash reproducible in 3.6.4 & 3.7.1 versions.

**Comment by anlinde** [comment]
Thanks, can you please provide a symbolicated crash report for this?

**Comment by oleg-ivaniv** [comment]
Last crash report:

Date/Time:       2015-07-08T09:45:27Z
Launch Time:     2015-07-08T08:07:12Z
OS Version:      iPhone OS 8.4 (12H143)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x195663270
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the table view after the update (3) must be equal to the number of sections contained in the table view before the update (2), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).'

Last Exception Backtrace:
0   CoreFoundation                       0x00000001835442d8 __exceptionPreprocess + 132
1   libobjc.A.dylib                      0x0000000194ea00e4 objc_exception_throw + 56
2   CoreFoundation                       0x0000000183544198 +[NSException raise:format:arguments:] + 112
3   Foundation                           0x00000001843f8ed4 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 108
4   UIKit                                0x00000001881a2c10 -[UITableView _endCellAnimationsWithContext:] + 9980
5   Kapp                                 0x000000010012f01c -[BITFeedbackListViewController willRotateToInterfaceOrientation:duration:] (BITFeedbackListViewController.m:398)
6   UIKit                                0x00000001882e3ec0 -[UIViewController viewWillTransitionToSize:withTransitionCoordinator:] + 336
7   UIKit                                0x00000001882e407c -[UIViewController viewWillTransitionToSize:withTransitionCoordinator:] + 780
8   UIKit                                0x00000001882dd144 +[UIViewController _performWithoutDeferringTransitions:] + 124
9   UIKit                                0x00000001882e4258 -[UIViewController _sendViewWillTransitionToSizeToPresentationController:withTransitionCoordinator:] + 228
10  UIKit                                0x00000001882e40c0 -[UIViewController viewWillTransitionToSize:withTransitionCoordinator:] + 848
11  UIKit                                0x00000001882dd144 +[UIViewController _performWithoutDeferringTransitions:] + 124
12  UIKit                                0x00000001882e84bc -[UIViewController(AdaptiveSizing) _window:viewWillTransitionToSize:withTransitionCoordinator:] + 536
13  UIKit                                0x000000018827a45c -[UIWindow _rotateToBounds:withAnimator:transitionContext:] + 488
14  UIKit                                0x000000018827b40c -[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:] + 1256
15  UIKit                                0x000000018827bb0c -[UIWindow _setRotatableClient:toOrientation:applyTransformToWindow:updateStatusBar:duration:force:isRotating:] + 356
16  UIKit                                0x000000018803ac30 -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] + 140
17  UIKit                                0x0000000188032698 __57-[UIWindow _updateToInterfaceOrientation:duration:force:]_block_invoke + 124
18  UIKit                                0x0000000187fbe380 -[UIWindow _updateToInterfaceOrientation:duration:force:] + 396
19  UIKit                                0x0000000187fbde60 -[UIWindow _updateInterfaceOrientationFromDeviceOrientation:] + 328
20  CoreFoundation                       0x00000001834ea2c4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 16
21  CoreFoundation                       0x0000000183427450 _CFXNotificationPost + 2056
22  Foundation                           0x0000000184356a80 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
23  UIKit                                0x0000000187fbdb34 -[UIDevice setOrientation:animated:] + 356
24  UIKit                                0x0000000187fbd7f0 -[UIApplication handleEvent:withNewEvent:] + 1628
25  UIKit                                0x0000000187fbd080 -[UIApplication sendEvent:] + 100
26  UIKit                                0x00000001880292c4 _UIApplicationHandleEvent + 696
27  GraphicsServices                     0x000000018cd2d194 _PurpleEventCallback + 708
28  GraphicsServices                     0x000000018cd2cc84 PurpleEventCallback + 40
29  CoreFoundation                       0x00000001834fba54 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 52
30  CoreFoundation                       0x00000001834fb9b4 __CFRunLoopDoSource1 + 432
31  CoreFoundation                       0x00000001834f9934 __CFRunLoopRun + 1636
32  CoreFoundation                       0x00000001834252d4 CFRunLoopRunSpecific + 392
33  GraphicsServices                     0x000000018cd2b6fc GSEventRunModal + 164
34  UIKit                                0x0000000188022f40 UIApplicationMain + 1484
35  Kapp                                 0x00000001000f14fc main (main.m:17)
36  libdyld.dylib                        0x000000019554aa08 start + 0

**Comment by anlinde** [comment]
Thanks, we'll check that.

**Comment by oleg-ivaniv** [comment]
Thank you! I'll also try to find a root reason of this crash.

**Comment by anlinde** [comment]
The problem is not related to deleting the app from the device. It is that data is arriving and getting updated on the device while a rotation is happening. So to reproduce the issue, the exact timing is very important.

**Comment by anlinde** [comment]
The linked commit does fix the crash when I simulated it locally.
