### ISSUE TITLE
Cocoapods Install fails to build

### ISSUE THREAD

**Issue by robertjpayne** [bitstadium/HockeySDK-iOS#182]
Reproduction Steps:

1. Create a new project
2. Add a Podfile with:

```
platform :ios, '8.0'
use_frameworks!

pod 'HockeySDK', '~> 3.7.1'
```

3. Run `pod install`
4. Open *.xcworkspace
5. Build

Expected Result:

Successful building of project

Actual Result:

Build fails with output:

```
Command /bin/sh failed with exit code 23

PhaseScriptExecution Copy\ Pods\ Resources /Users/robertjpayne/Library/Developer/Xcode/DerivedData/HelloWorld-dftlbyabhkkjlvarxarsiwhhneee/Build/Intermediates/HelloWorld.build/Debug-iphoneos/HelloWorld.build/Script-32E197776D2C07829B365B4E.sh
    cd /Users/robertjpayne/Desktop/HelloWorld
    /bin/sh -c /Users/robertjpayne/Library/Developer/Xcode/DerivedData/HelloWorld-dftlbyabhkkjlvarxarsiwhhneee/Build/Intermediates/HelloWorld.build/Debug-iphoneos/HelloWorld.build/Script-32E197776D2C07829B365B4E.sh

/Users/robertjpayne/Library/Developer/Xcode/DerivedData/HelloWorld-dftlbyabhkkjlvarxarsiwhhneee/Build/Products/Debug-iphoneos/HockeySDKResources.bundle
building file list ... rsync: link_stat "/Users/robertjpayne/Library/Developer/Xcode/DerivedData/HelloWorld-dftlbyabhkkjlvarxarsiwhhneee/Build/Products/Debug-iphoneos/HockeySDKResources.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

Unsure if this is really HockeySDK's issue or not but it's the resource bundle failing to be copied properly.

**Comment by anlinde** [comment]
Hi Robert,

I just tried this and everything works fine using CocoaPods 0.37.2. Which version are you using? Also did you make a clean build before?

**Comment by robertjpayne** [comment]
@anlinde may have been derived data -- Same version, did it on a fresh project. Let me get back to you in just a minute.

**Comment by robertjpayne** [comment]
Not really sure what happened -- something was horribly awry as I cleaned, used a brand new project and it was bugging out.

I've fixed it now through some combo of force re-installing gems or something. Apologies.

**Comment by Cinamonas** [comment]
I have the same issue, using 3.7.1 HockeySDK and 0.37.2 CocoaPods. I tried removing `DerivedData`, `Pods`, cleaning the project, but nothing helps so far.

```
<...>/Build/Products/Debug-iphonesimulator/HockeySDKResources.bundle
building file list ... rsync: link_stat "<...>/Build/Products/Debug-iphonesimulator/HockeySDKResources.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

**Comment by anlinde** [comment]
Hi,

please try removing the SDK completely and then adding it again. It works flawlessly in all of our tests.

**Comment by Cinamonas** [comment]
Hi, I tried reinstalling the pod, but it didn't help.

But I solved the issue just now by reinstalling CocoaPods :confused:

**Comment by Cinamonas** [comment]
Hi, I tried reinstalling the pod, but it didn't help.

But I solved the issue just now by updating CocoaPods to v0.38.0.beta.2 :confused:
