### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by ocgully** [bitstadium/HockeySDK-iOS#186]
### Introduction:

In our project we want to use Authentication with WebAuth to validate that the app is authorized for use with an Enterprise Provisioning Profile. We've started integrating the HockeyApp authorization feature into our project but it does not appear to work as intended. Following the instructions here http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/authenticating-users-on-ios, we were able to get the "sign in with safari" dialog to appear, and make a round trip (app->safari->sign in->app). I'm just now starting to dig into the actual code, so please excuse any erroneous assumptions.
### Issues:
1. After authorizing once, it seemed to persist across multiple app installs, even when deleting the app.
   1. My coworker said that it seemed like it was stored in the keychain.
   2. He also said that they tried changing the Bundle Identifier, and the App Identifier in code, but it still automatically authorized on subsequent installs.
   3. This also leads to the question: Does one authorized HockeyApp application result in authorization for all HockeyApp applications? Even ones the user is not specifically assigned to?
   4. Expected Behavior: The authorization is not persisted across installs, and it correlates to the HockeyApp identifier and the Bundle Identifier. If either changes then the authorization session should be voided. Additionally, authorizing one app should not authorize all apps.
2. When the user is not authorized in HockeyApp, Safari would signed into the website normally showing the landing page. There was no link back to the app, no message to indicate that they are not authorized to use the app, nothing to indicate to the user of expected behavior.
   - Expected Behavior: If the user signs in but is not authorized they should be linked back to the app, as they are when authorized, to receive a message indicating that they are not authorized, with an option to try logging in again.
3. When using BITAuthenticatorAppRestrictionEnforcementOnAppActive, after previously using OnLaunch, and with a persisted authorization, we do not receive a dialog on first launch to sign in, nor do we see one stating that the user is not authorized. However, after about 45+ seconds, we receive a dialog that states "Failed to authorize. Please try again or contact the developer of this app."
   1. Clicking "OK" on this dialog, causes a second dialog to appear with the same text.
   2. Clicking "OK" on the second dialog, causes it to go away and allows the user complete access to the app. The dialog will appear again after about another 45+ seconds. It functions more as a nag screen than blocking usability.
   3. Backgrounding the app will also cause this dialog to appear.
   4. Expected Behavior: If the authorization session is not valid OnLaunch/OnAppActive then a dialog should be shown immediately prompting the user to sign in. The player is never allowed to progress if they are not authorized. It would also be nice to receive a callback when authorization fails, in the event that we want to execute special logic.
### Feature Requests:
1. It would be nice to have a new RestrictionEnforcement that allows for an authorization timeout duration.
   - Expected Behavior: Configurable number of seconds from last authorization, after the time expires it results in a blocking dialog requesting authorization again. It would also be nice to have a toggle for choosing if the dialog can show up at any time, or only OnAppActive.
2. Ability to set the background of the dialog screen views to black to completely obstruct anything that is happening in the background. After all, the user is not yet authorized to see that content.
   - Expected Behavior: The dialogs completely block the user from seeing anything that would otherwise be visible.
### Initialization code

(excluding the openURL callback, and the changes made to the Info.plist):

``` objective-c
    [[BITHockeyManager sharedHockeyManager] configureWithIdentifier:m_appID delegate:nil];
    [BITHockeyManager sharedHockeyManager].authenticator.webpageURL = [NSURL URLWithString:AUTHENTICATION_URL];
    [BITHockeyManager sharedHockeyManager].authenticator.restrictApplicationUsage = true;
    [BITHockeyManager sharedHockeyManager].authenticator.restrictionEnforcementFrequency = BITAuthenticatorAppRestrictionEnforcementOnAppActive;
    [[BITHockeyManager sharedHockeyManager].authenticator setIdentificationType:BITAuthenticatorIdentificationTypeWebAuth];
    [[BITHockeyManager sharedHockeyManager] startManager];
    [[BITHockeyManager sharedHockeyManager].authenticator authenticateInstallation]; 
```

**Comment by anlinde** [comment]
Hi,

thanks for the detailed description. First off a question from my end: why do you set the `webpageURL` property? Which address are you setting it to?

Regarding your issues:

1. Keychain:

  1. The auth token is stored in the keychain using the bundle identifier of the app, see https://github.com/bitstadium/HockeySDK-iOS/blob/develop/Classes/BITHockeyHelper.m#L120
  2. The value is not deleted from the keychain by our SDK, since it is not possible to detect this event in any way
  3. Authorization is done per application since it uses the bundle identifier, see the referenced code above. I assume your colleague did something wrong and Xcode didn't really take the bundle identifier change.
2. We did not design the behaviour as you expect it. We have no plans to change the current behaviour. The user can also easily go back to the app with the iOS app switching feature.
3. As the user is already authorized, why should it ask for authorization again? Changing the auth method or frequency doesn't delete the keychain, as we can't detect this and don't store the auth token depending on the auth method. So if you authenticate a user with any method, then change the auth method and don't remove the user from the app, then the token is still valid.

Regarding your feature requests: Thanks for the requests, we'll put it on our long list, but we currently don't have any plans to implement this. But we are always open to receive pull requests if you want to implement it.

**Comment by ocgully** [comment]
Thanks for the quick response Andreas!

Q: Why do you set the webpageURL property?
A: We have licensed HockeyApp for enterprise usage, as such we must forward authorization requests to our internal servers running the HockeyApp backend.

1. Keychain - Good to know, thanks!
2. Unauthorized Login Flow - Fair enough. I can understand the expectation that unauthorized users would not have access to the app, and therefore this flow should not generally happen. 
3. Perhaps our use case is different than the normal use case, I cannot say. However, it's our preferred use case to be able to modify authorization enforcement across builds (even more preferred would be server authoritative authentication, so it can be modified without issuing new builds). Early builds may be extremely sensitive and confidential (authorization on every activation), where as internal betas may be more relaxed. We also want to protect against previously authorized parties; such as those who have left the company, or are no longer a development partner, or even internally have changed projects and no longer need access. This is why #2 (Unauthorized login flow) was important for us, as a way of relaying this information to the user.
   * If this is ever revisited I would recommend storing authorization as session data, instead of whether the user is authorized or not. In this manner, you could check the latest session data against whatever the current enforcement policy is. If authorized 8 months ago satisfies the OneTimeOnLaunch enforcement policy, then no reauthorization would be requested. If it does not satisfy the OnEveryAppActivation/SessionDuration enforcement policy, then the previous session would be revoked and they would be asked to reauthorize again.
   * Additionally, it would be nice if HockeyApp provided a way of revoking the session/authorization. That would allow us during upgrades, which we detect ourselves for other reasons, to force reauthorization if so desired.

For our use case of HockeyApp these expectations and features are necessary. I will likely be implementing much of what I discussed above and given the proper authorization(heh), I will be happy to issue pull requests.

Thanks again!

**Comment by Autoc0diq** [comment]
Andreas,

How is the auth refresh if a user is later to a new team or when new tags are associated with him?
We have a case where a previously authenticated user is not getting prompted for new restricted builds but works after clearing keychain and reauthorizing user.
(We did change from an automatic auth to manual auth in between builds and it started failing when we swtiched to manual).

**Comment by anlinde** [comment]
@Autoc0diq: could you please create a new ticket and describe in more detail what you are doing in code and where in the process you are running into issues.

Thanks!

**Comment by TroubleMakerBen** [comment]
We haven't heard back in a long time. I'm closing this issue.
