### ISSUE TITLE
Does not build with Xcode7 Beta5

### ISSUE THREAD

**Issue by pvegh** [bitstadium/HockeySDK-iOS#187]
Currently the "enable bitcode" flag on the project must be explicitely turned off in order to build with HockeySDK.

Xcode7 Beta5, Cocoapods 0.38.2

```
Pods/HockeySDK/HockeySDK-iOS/HockeySDK.embeddedframework/HockeySDK.framework/HockeySDK(BITHockeyAppClient.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by anlinde** [comment]
Yes, this is known and we are working on it in the iOS 9 feature branch. Still not enabled since a Bitcode enabled version of PLCrashReporter is pending.

**Comment by anlinde** [comment]
You can use the 3.8 Beta 1 release or the iOS 9 feature branch: https://github.com/bitstadium/HockeySDK-iOS/tree/feature/iOS9-Updates

**Comment by pvegh** [comment]
Thanks for the update!
That branch seems to have another problem when using it as a pod, so I opened a new issue for that:
https://github.com/bitstadium/HockeySDK-iOS/issues/192

**Comment by amitmawkin** [comment]
is there an update to issue the above link results in 404

**Comment by lumaxis** [comment]
@amitmawkin The current SDK version 3.8.5 has been working reliably with current versions of Xcode for a while now. Are you experiencing any issues?

**Comment by amitmawkin** [comment]
@lumaxis maybe the open source project I was trying to build is using an old version, 
I was trying to run the build via jenkins using a continuous integration process and was running into this , so i will take the latest fork and see if that helps.

thanks again for your quick response

**Comment by lumaxis** [comment]
@amitmawkin Sure, no problem. If you're running into issues with current version, let me know and I'll take a look.
General note though: There is currently no known upside to having Bitcode enabled for iOS apps in the first place and it only causes trouble. So just switching it off overall might spare you some problems.
