### ISSUE TITLE
`synchronize` is generally considered bad practice

### ISSUE THREAD

**Issue by hfossli** [bitstadium/HockeySDK-iOS#188]
Synchronize is periodically invoked automatically so it rarely needs to be called manually. It is generally considered excessive to call it manually. 

<img width="472" alt="screen shot 2015-08-20 at 14 52 42" src="https://cloud.githubusercontent.com/assets/3652587/9383672/24f96404-474b-11e5-9f19-fc71c20543d9.png">

I get it if the app is crashing and you need to ensure user defaults is synchronized, but is this IO really necessary in all cases? You are assuming the user defaults for any application using HockeyApp is quite lightweight, which may or may not be true.

**Comment by lumaxis** [comment]
Thanks for writing in! Yes, you're absolutely right. We're aware of the general performance implications of using `synchronize` in many places but still feel that in most of these places we need to make sure that the information is persisted on disk. I think we will revisit this in a future update. Maybe our own SDK-specific file as a better solution to this problem.

**Comment by hfossli** [comment]
Yep. Dispatch to a background queue and save to a lightweight file will be just as reliable as the current implementation.

**Comment by anlinde** [comment]
Simply doing stuff in a background queue doesn't solve the issues in those places. Most of those need the writing to happen at exact that time on the main thread.

As mentioned, we'll re-evaluate all those and come up with a solution that won't use `NSUserDefaults` in the first place.
