### ISSUE TITLE
How does `BITHockeyNetworkDidBecomeReachableNotification` work?

### ISSUE THREAD

**Issue by 0xced** [bitstadium/HockeySDK-iOS#189]
The documentation mentions `BITHockeyNetworkDidBecomeReachableNotification` in both BITFeedbackManager.h and HockeySDK.h but it’s not clear if it’s the Hockey SDK’s responsibility or the developer’s responsibility to post it.

The `BITHockey` prefix makes me think it should be the Hockey SDK’s responsibility but a quick look at the source code (version 3.7.2) reveals that this notification is never posted. Is this the developer’s responsibility to post this notification? If yes, then the documentation should be very explicit about it.

**Comment by anlinde** [comment]
Hi,

it is an option for the app developer to trigger additional points where the HockeySDK can try to send pending crash reports or feedback messages. I made it more clear in the following commit: https://github.com/bitstadium/HockeySDK-iOS/commit/1c221668de3eadee43004b397e5d1ae0663b6554

Thanks!

**Comment by 0xced** [comment]
Thanks for the clarification. 👍🏻
