### ISSUE TITLE
Cocoapods: Pod from the os9-updates branch broken

### ISSUE THREAD

**Issue by pvegh** [bitstadium/HockeySDK-iOS#192]
The pod from the ios9-updates branch seems to be currently broken, there is only the readme.md file in there after installing the pod and nothing else.

  pod 'HockeySDK', :git => 'https://github.com/bitstadium/HockeySDK-iOS.git', :branch => 'feature/iOS9-Updates'

I mighty have done something wrong though.

**Comment by lumaxis** [comment]
To use a prerelease version with CocoaPods, you need to add the prerelease version number in your Podfile. So simply putting `pod 'HockeySDK', '~> 3.8-Beta'` will work and get you an iOS 9-compatible version :+1:

**Comment by pvegh** [comment]
Thanks for that one, it works indeed.
I don't understand yet why specifying the branch was not good enough in this case, since I am using that notation for other pods to get their swift-2.0 branches successfully.
I mean HockeySDK was even pulled with the new beta version, it was just not present in the Pods folder after the update.

**Comment by lumaxis** [comment]
The explanation is very simple :) Our default pod uses our compiled SDK which is distributed as a binary. So when you point you Podfile to the branch it's looking for the binary release there which it of course can't find.
To use a branch directly, you would need to switch to our alternate `HockeySDK-Source` pod.

**Comment by pvegh** [comment]
Yeah ok that explains it pretty straightforward :) Thanks!

**Comment by lumaxis** [comment]
Anytime! Be sure to let us know of you run into any issues with the 3.8 Beta. Happy to help out :relaxed:
