### ISSUE TITLE
Textfield in BITFeedbackComposeViewController is buggy after device rotation  

### ISSUE THREAD

**Issue by JensDee** [bitstadium/HockeySDK-iOS#196]
When starting to write a text in the BITFeedbackComposeViewController and then rotating the device to landscape, the textfield width seems to change. Some of the text per line disappears. You write in an invisible area. When continuing to type, at some point there will be another line break.
This phenomenon persists in landscape format. It seems the line width is even larger then the landscape view width.

See screenshots attached. The text hello world has been written approx. 9 times. All text after number 6 was written without seeing it (in both portrait and landscape format).

We first noticed this with SDK version 3.6.4
It still occurs with 3.7.1 and on the iOS9-Updates branch.

![img_1160](https://cloud.githubusercontent.com/assets/4264933/9745468/601388e0-5672-11e5-8073-3c4895323c6f.jpg)
![img_1161](https://cloud.githubusercontent.com/assets/4264933/9745470/604a7102-5672-11e5-9282-42a08a6221c1.jpg)
![img_1162](https://cloud.githubusercontent.com/assets/4264933/9745521/a23f3426-5672-11e5-8583-a4eafc9a6451.jpg)

**Comment by lumaxis** [comment]
Thanks @JensDee for bringing this up! We'll look into this and come up with a fix soon :ok_hand:

**Comment by anlinde** [comment]
Thanks for the details. We were able to reproduce and fix it. It will be part of the next update.

**Comment by JensDee** [comment]
Excellent. Is there already a schedule for the next update?

**Comment by anlinde** [comment]
We just released version 3.8 RC 1 which contains this fix: http://hockeyapp.net/blog/2015/09/10/hockeysdk-ios-3-8-rc-1-release-notes.html

Important: This version requires Xcode 7 for building!
