### ISSUE TITLE
Undefined symbols for architecture x86_64 with Xcode 7 and iOS 9 SDK

### ISSUE THREAD

**Issue by sunflash** [bitstadium/HockeySDK-iOS#198]
"3.8 Beta 1" and "3.8 Release Candidate 1" binary is not fully compatible with Xcode 7 and iOS 9 SDK
<img width="571" alt="screen shot 2015-09-12 at 17 35 18" src="https://cloud.githubusercontent.com/assets/4181292/9832227/b1a90388-5974-11e5-9f38-749df30cf246.png">

**Comment by anlinde** [comment]
Hi, we can not reproduce this. How do you integrate the SDK? Can you reproduce this in a sample project and provide that to us so we can analyze this?

Thanks

**Comment by sunflash** [comment]
Hi

I found the issue, that I forgot to add libc++
Thanks :)

**Comment by sivamoorthykutty** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TWTRAPIClient", referenced from:
      type metadata accessor for __ObjC.TWTRAPIClient in SignupViewController.o
  "_OBJC_CLASS_$_TWTRShareEmailViewController", referenced from:
      type metadata accessor for __ObjC.TWTRShareEmailViewController in SignupViewController.o
  "_OBJC_CLASS_$_Twitter", referenced from:
      type metadata accessor for __ObjC.Twitter in SignupViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by anlinde** [comment]
This issue is not related to HockeySDK as it clearly references a Twitter SDK.

**Comment by varunempire** [comment]
This error is not about Twitter SDK including x86_64 architecture  will solve this problem

**Comment by TroubleMakerBen** [comment]
@varunempire @sivamoorthykutty
I'm glad you solved your problem. Nonetheless, none of the errors above is related to the HockeySDK as it clearly mentions the Twitter SDK as in **TWTRAPIClient** above.

**Comment by iostechinfo** [comment]
Simple trick here: Go -> Go To Folder "/Library/Developer/Xcode" delete Derived data next clean your project then Run .
