### ISSUE TITLE
Initializing Hockey from a Keyboard extension causes the Keyboard to appear after a long pause.

### ISSUE THREAD

**Issue by aventurella** [bitstadium/HockeySDK-iOS#200]
When I initialize Hockey from a Keyboard Extension, the keyboard takes a long time, 5-10 seconds to come up. If I do not initialize Hockey the keyboard appears in about 1 sec, maybe less.

When I try to initialize Hockey in the background:
```swift
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)){
self.initializeHockey()
}
```

The keyboard extension just crashes.
If I slightly defer it's initialization:

```swift
dispatch_async(dispatch_get_main_queue()){
self.initializeHockey()
}
```

I get an acceptable display speed.

Any guidance/best practice on when to initialize Hockey in a Keyboard Extension?

**Comment by anlinde** [comment]
Thanks, some notes:

1. We haven' tested this with a keyboard extension yet. Could you provide a sample project that reproduces the issue?
2. Are you using the crash only extension build we provide? https://github.com/bitstadium/HockeySDK-iOS#24-set-up-the-sdk-in-xcode
3. Calling this asynchronously will not let you capture crashes that happen early.
4. Could you provide us a Xcode Instruments recording with the Time Profiler, which would show you and us exactly where and what is taking too much time in the code.

**Comment by lumaxis** [comment]
Hey @aventurella, do you still need help with this? :relaxed:

**Comment by aventurella** [comment]
I'm good, thanks!
