### ISSUE TITLE
Check the "Allow app extension API only" in the xcode project

### ISSUE THREAD

**Issue by aventurella** [bitstadium/HockeySDK-iOS#201]
Compile time warnings about not having that box checked when using Hockey within extensions

**Comment by anlinde** [comment]
Are you using the build configuration `ReleaseCrashOnlyExtensions` and disabling all features but CrashReporting in `HockeySDKFeatureConfig.h`.

The much easier way would be to use the binary we provide with exactly these build settings instead of building it yourself.

**Comment by aventurella** [comment]
Sure, I can do that, I figured, since Hockey allows a Carthage build, whatever was the best settings would already be set in the Shared Scheme that Carthage uses to build.

**Comment by anlinde** [comment]
This is not possible, since we that build setting can not be enabled for the build for iOS apps. Hence you need to define the build configuration and can't use the default one.
