### ISSUE TITLE
ATS iOS 9 support in BITStoreUpdateManager

### ISSUE THREAD

**Issue by NKorchagin** [bitstadium/HockeySDK-iOS#206]
Hi.

Are you sure that request with this url https://github.com/bitstadium/HockeySDK-iOS/blob/3.8.2/Classes/BITStoreUpdateManager.m#L345 will be handled correctly by iOS 9 with latest ATS changes. Did you test it?

**Comment by anlinde** [comment]
Hi,

thanks for the notice. Apple redirects the call to https and when using `nscurl --ats-diagnostics ` with an `http://`URL it also passes all the tests.

We'll adjust the URL to https in the code, but it should work just fine with the existing URL too.

Best,
Andreas

**Comment by lumaxis** [comment]
Hey @NKorchagin, we just released [version 3.8.3](https://github.com/bitstadium/HockeySDK-iOS/releases/tag/3.8.3) which changes this URL to `https` :)
