### ISSUE TITLE
Pod install of hockeysdk is failing travis builds

### ISSUE THREAD

**Issue by wedgybo** [bitstadium/HockeySDK-iOS#208]
I'm not 100% sure how to look at sorting this, or if it's a problem with our end or not.

I can install the sdk locally just fine using pod install. When we run it on Travis, we're getting a failure when trying to copy the PNG files.

We're using fastlane to create the build so I'm not quite sure if that is having an effect at all. Just seems odd that the install and build works fine locally.

Any help or advice would be appreciated.

**Cmd**
```
[16:49:36]: set -o pipefail && xcodebuild -workspace './Mallzee.xcworkspace' -scheme 'Mallzee' -destination 'generic/platform=iOS' -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2015-10-07/Mallzee:DEV 2015-10-07 16.49.36.xcarchive' clean archive CODE_SIGN_IDENTITY='iPhone Developer: Jamie XXX (XXX)' | tee '/Users/travis/Library/Logs/gym/Mallzee:DEV-Mallzee.log' | xcpretty
```

**Output**
```
▸ Building Pods/HockeySDK-HockeySDKResources [Release]
** ARCHIVE FAILED **
The following build commands failed:
CopyPNGFile /Users/travis/Library/Developer/Xcode/DerivedData/Mallzee-cnvpomjkanxijneyigsvhqkluzeo/Build/Intermediates/ArchiveIntermediates/Mallzee/IntermediateBuildFilesPath/UninstalledProducts/HockeySDKResources.bundle/Arrow.png HockeySDK/HockeySDK-iOS/HockeySDK.embeddedframework/HockeySDK.framework/Versions/A/Resources/HockeySDKResources.bundle/Arrow.png
(1 failure)
[16:50:44]: Exit status: 65
```

**Comment by lumaxis** [comment]
Thanks for reporting this! Before I can start investigating this further could you please try two things:
- Try running the exact same xcodebuild command on your local machine (if you haven't already)
- Remove xcpretty and see if that gives you different log messages. In my experience, xcpretty sometimes swallows important parts of error messages.

**Comment by wedgybo** [comment]
I've tried running it locally and it's working fine, which is what's confusing me. We have the pods folder checked in so the versions should be identical when it's trying to compile it but it always just seems to fail on travis. Because you can't get on to the machine it's tricky to figure out why.

Also because we're using fastlane I can't really change the command it executes as it's generated by the gym component of it.

**Comment by lumaxis** [comment]
Huh, very weird issue. Have you tried disabling xcpretty to see if there's any more helpful logging going on there?
@krausefx Have you maybe seen something like this ever? Any ideas?

**Comment by wedgybo** [comment]
I've tried disabling it locally, but the problem doesn't seem to show there. Everything builds fine. It must be something environmental on travis but I've no idea what it could be.

I can't see an easy way of disabling xcpretty inside gym. I'll take a look tomorrow at the code to see if there's a way to remove it and see if that throws up more information

**Comment by anlinde** [comment]
Did you try checking the pods into your repository instead of downloading and installing them on every build? Maybe that helps.

**Comment by wedgybo** [comment]
Yea we do that already that's why I'm confused to be honest. Comparing the logs from my local build to my travis one, it seems on travis it does some stuff with cleaning the pods and the like that doesn't happen locally so I'll look into that this morning. I'm sure it's a problem our end but I figured someone might have come across it before. 

Thanks everyone for their help so far!

**Comment by 0xced** [comment]
You can use xcpretty and still have full logs:
```bash
set -o pipefail
xcodebuild [flags] | tee xcodebuild.log | xcpretty -c && rm xcodebuild.log
```
(adapted from [Raw xcodebuild output](https://github.com/supermarin/xcpretty#raw-xcodebuild-output) in xcpretty’s documentation)

Then in your `.travis.yml` add this to have access to the full log in case of failure:
```yml
after_failure:
  - cat xcodebuild.log
```

Also, make sure you are using the same Xcode version locally and on Travis, xcodebuild may behave differently. Use the [`osx_image`](http://blog.travis-ci.com/2015-07-08-xcode-6-4-now-available/) [key](http://blog.travis-ci.com/2015-09-09-xcode7-gm/) in your `.travis.yml` file.

**Comment by wedgybo** [comment]
Ok. So I'm an idiot. Some pods were checked in then at some point the Pods folder was added to gitignore which I wasn't aware of so the Hockey pod wasn't there at all. Sorry if I wasted anyone's time with this but thanks for the help!

@0xced That's useful information. Thanks for that!
