### ISSUE TITLE
Add support for Chinese Traditional language 

### ISSUE THREAD

**Issue by kshin** [bitstadium/HockeySDK-iOS#214]
Hi Guys, 

As for now HockeyApp iOS SDK supports only Chinese Simplified language and I would like to see a support for Chinese Traditional language and I think at least at the beginning, SDK can use Simplified translations as Traditional.

**Comment by lumaxis** [comment]
Thanks @kshin for the suggestion! I don't think we have any plans for supporting additional languages for the very immediate future but I'll definitely discuss this with people internally and see what our plans are for expanding translations :relaxed:

**Comment by anlinde** [comment]
Hi,

thanks for your suggestion. As @lumaxis already mentioned we currently have no plans to extend the amount of languages we support out of the box. This might change in the future though.

Best,
Andreas
