### ISSUE TITLE
Bold "Send" instead of "Don't Send" (iOS 9)

### ISSUE THREAD

**Issue by livings124** [bitstadium/HockeySDK-iOS#216]
In UIAlertController (and UIAlertView), the cancel button is bolded by default. iOS 9 added preferredAction: to UIAlertController, allowing a different button to be bolded.

"Send Report" should be bolded using this method, since that option makes more sense being emphasized.

**Comment by anlinde** [comment]
We removed the use of `UIAlertController` for now, since it has way too many issues.

"Don't send" is assigned to the cancel action, which is the one that gets rendered in bold in `UIAlertView`. This is correctly used according to the API and documentation.
