### ISSUE TITLE
Changelog for v3.8.3

### ISSUE THREAD

**Issue by tommeier** [bitstadium/HockeySDK-iOS#217]
<img width="540" alt="screen shot 2015-10-23 at 1 54 38 pm" src="https://cloud.githubusercontent.com/assets/19973/10683422/b63683d8-798d-11e5-88e6-d5e2db08e34f.png">

Not provided yet?

**Comment by lumaxis** [comment]
Hey @tommeier! Thanks for the report. Somehow, our docs generation script didn't do what it should. Will be fixed soon.

**Comment by tommeier** [comment]
Thanks @lumaxis :)

**Comment by lumaxis** [comment]
There you go @tommeier! :) http://hockeyapp.net/help/sdk/ios/3.8.4/docs/docs/Changelog.html

**Comment by tommeier** [comment]
Perfect :dancer:
