### ISSUE TITLE
Unable to build v3.8.3 with cocoapod

### ISSUE THREAD

**Issue by tommeier** [bitstadium/HockeySDK-iOS#218]
<img width="894" alt="screen shot 2015-10-23 at 2 17 48 pm" src="https://cloud.githubusercontent.com/assets/19973/10683738/e427a5ee-7990-11e5-924b-ea88f42beb15.png">

3.8.2 works, this is with XCode 7.1 (El Capitan).

**Comment by x2on** [comment]
Same problem here!

**Comment by lumaxis** [comment]
Hey guys,

I just pushed an update that fixes this issue which should be propagating through CocoaPods as we speak. Please give updating to 3.8.4 a try and let me know if something still doesn't work.

Sorry for the hiccup!
