### ISSUE TITLE
BITFeedbackComposeViewController issues with rotation

### ISSUE THREAD

**Issue by ob1techno** [bitstadium/HockeySDK-iOS#220]
Looks like there are still some issues with rotation in the BITFeedbackComposeViewController - the "Add Image" button is often displayed off centre and sometimes in landscape view, the "Add Image" button appears in portrait position.

**Comment by lumaxis** [comment]
Can you give us a bit more information about your setup? OS version, device(s), SDK version? Thanks!

**Comment by ob1techno** [comment]
HockeySDK 3.8.4 (release notes suggest the issue was fixed in 3.8)
iOS 9.1 SDK
Xcode 7.1
Seeing this on a variety of iPhone models/OS versions, but mostly testing on iPhone 5 running iOS 9.0.2 and iPhone 6s running iOS 9.1

**Comment by lumaxis** [comment]
Hey @ob1techno!
I've looked at this over the last week and although I tried several different apps and setups, I couldn't reproduce this issue. Do you have any more detailed steps I can use to repro or maybe even a specific demo project that shows the behaviour? Thanks!

**Comment by ob1techno** [comment]
Thanks @lumaxis - I'll see if I can put together a demo project and send it over

**Comment by lumaxis** [comment]
@ob1techno Any updates on this? :relaxed:

**Comment by anlinde** [comment]
@ob1techno Got any updates to reproduce this issue? Thanks.
