### ISSUE TITLE
Protecting keychain items

### ISSUE THREAD

**Issue by xiaoyongwu** [bitstadium/HockeySDK-iOS#226]
Hi,
We are using HockeySDK in our iOS app and our mobile app security scanning identified an issue as "Keychain Items Using Weak Protection Class - AccessibleAlways".  We noticed that it is coming from the following lines in the SDK.
https://github.com/bitstadium/HockeySDK-iOS/blob/a1e7a782122ffcdd32eefafdf5d6c3e28c39bbeb/Classes/BITKeychainUtils.m#L125-L127 

+ (BOOL) storeUsername: (NSString *) username andPassword: (NSString *) password forServiceName: (NSString *) serviceName updateExisting: (BOOL) updateExisting error: (NSError **) error {
  return [self storeUsername:username andPassword:password forServiceName:serviceName updateExisting:updateExisting accessibility:kSecAttrAccessibleAlways error:error];
}

As you can see, the keychain items are stored with kSecAttrAccessibleAlways. It would be better if we can protect those items while the device is locked following documents here: https://developer.apple.com/library/ios/documentation/security/Reference/keychainservices/Reference/reference.html.

**Comment by anlinde** [comment]
We can't do that, since otherwise it won't work that run on the background or where the device is in an unlocked state but the app or extension still needs to work.

**Comment by xiaoyongwu** [comment]
I understand the SDK needs to support different use cases. Is it possible to make this configurable so we can configure for our usage?

**Comment by anlinde** [comment]
As of now, you can fork the SDK and modify it yourself and make your own build. We'll see if it makes sense to make this configurable, but this nothing we can provide in the short term sadly.
