### ISSUE TITLE
SDK will crash the app if hockey app id is nil or blank string

### ISSUE THREAD

**Issue by zmian** [bitstadium/HockeySDK-iOS#228]
```swift
func setupHockeySDK() {
    ...
    BITHockeyManager.sharedHockeyManager().configureWithIdentifier(hockeyAppId)
    ...
}
```

Above snippet will crash the app if `hockeyAppId` is `nil` or **blank** string with following: `Fatal error: unexpectedly found nil while unwrapping an Optional value`

Workaround is to add 

```swift
func setupHockeySDK() {
    guard let hockeyAppId = hockeyAppId else { return }
    ...
    BITHockeyManager.sharedHockeyManager().configureWithIdentifier(hockeyAppId)
    ...
}
```

Would it be possible to audit the api headers and add nullability audit checks. But would still require the api to check for blank strings
```objc
NS_ASSUME_NONNULL_BEGIN
NS_ASSUME_NONNULL_END
```

**Comment by lumaxis** [comment]
Hey @zmian,

thanks for pointing this out. Nullability Annotations is on out long todo list but no ETA yet :)
I'll look into why this is crashing because that should not happen. Please be aware though that our SDK does not work if the identifier is not valid or empty.

**Comment by zmian** [comment]
Thanks for quick reply.

Make sense without identifier the SDK wouldn't work but it should't crash the app. Kinda meta... crash logger is crashing the app :D

**Comment by lumaxis** [comment]
Yes, definitely not. We put a lot of effort into making sure that our SDK never crashes.
My guess is that this is a weird Swift-conversion thing which we haven't run into yet :/

**Comment by lumaxis** [comment]
@zmian In your example, how are you initializing `hockeyAppId`? Because in my first try I couldn't reproduce the crash.

**Comment by zmian** [comment]
```swift
var hockeyAppId: String? { return "xxxx" }
```

`xxxx` represents a value coming from plist either local or remote. It makes sure that `hockeyAppId` has some value present before `setupHockeySDK()` is called.

Only reason why i found this crash was when I was debugging and accidentally put erased the `hockeyAppId` in plist to blank string.


to reproduce this error try this:

```swift
    private func setupHockeySDK(hockeyAppId: String?) {
        guard let hockeyAppId = AppConstants.hockeyAppId else { return }
        BITHockeyManager.sharedHockeyManager().configureWithIdentifier(hockeyAppId)
        // Disable "[HockeySDK] WARNING: Detecting crashes is NOT enabled..." log
        if BITHockeyManager.sharedHockeyManager().crashManager.isDebuggerAttached() {
            BITHockeyManager.sharedHockeyManager().disableCrashManager = true
        }
        BITHockeyManager.sharedHockeyManager().crashManager.crashManagerStatus = BITCrashManagerStatus.AutoSend // Auto-submit crash reports
        BITHockeyManager.sharedHockeyManager().startManager()
        BITHockeyManager.sharedHockeyManager().authenticator.authenticateInstallation()
    }
```

then call it:

```swift
let hockeyAppId = ""
setupHockeySDK(hockeyAppId)
```

**Comment by lumaxis** [comment]
I'm not sure what's going here.No matter if I pass in a `String?` or `String!`, both containing `nil`, I don't get the crash.
Can you please check what type `hockeyAppId` is when you pass it in before a crash is happening?

**Comment by zmian** [comment]
I'll try to set up test project tomorrow to reproduce this error in that. Thank you for looking in to this.

**Comment by lumaxis** [comment]
That would be perfect! Thanks for your help in tracking this down :)

**Comment by lumaxis** [comment]
Hey @zmian, is this still an issue for you? Any updates? 🙂

**Comment by lumaxis** [comment]
I'm closing this since I haven't heard back from you in over a month. Feel free to re-open anytime :relaxed:
