### ISSUE TITLE
Cannot disable some debug logs in BITCrashManager

### ISSUE THREAD

**Issue by anass-b** [bitstadium/HockeySDK-iOS#241]
in BITCrashManager.m (line: 1168):
```
NSLog(@"[HockeySDK] WARNING: Detecting crashes is NOT enabled due to running the app with a debugger attached.");
```

Could you please use BITHockeyLog() instead of NSLog() ? so then I can set [BITHockeyManager sharedHockeyManager].isDebugLogEnabled to NO and disable this warning if I don't want to see Hockey SDK logs in my console while debugging, and therefore I will not have my console window in Xcode open each time because of this message.

Btw, there are many lines of code which are still using NSLog instead of BITHockeyLog(). It would be nice to change them too.

Thanks

**Comment by anlinde** [comment]
Hi, thanks for your feedback.

We are using NSLog in cases we experience situations where our users should be informed directly about issues without requiring them to enable debug logging, which itself shows a lot more information.

Your posted example is a common case where developers don't understand why when testing the SDK they won't see crash reports in HockeyApp. Most don't even look into the documentation to find the setting to enable debug logging and thus cause a lot of effort to explain what and why things are happening.

If I recall correctly, we haven't gotten many (hardly any) to change this logging behaviour, as it is also not turned on in the App Store environment. We'll discuss if we want to change the behaviour and move those also to the debug log property.

Thanks,
Andreas

**Comment by anlinde** [comment]
Just a quick thought: you could also disable crash reporting for your debug builds as a workaround using something like this:

```
...
#ifdef DEBUG
[[BITHockeyManager sharedHockeyManager] setDisableCrashReporting: YES];
#endif
[[BITHockeyManager sharedHockeyManager] startManager];
...
```

**Comment by anass-b** [comment]
@anlinde Thanks for clarification, I can now understand the reason behind this.
For the snippet of code you provided, it will work perfectly for all other logs except the ones with NSLog(), but unfortunately I need the ones with NSLog() to be disabled.
I hope in the future you can provide a separate property, something like "criticalLogsEnabled" which is equal to "YES" by default, and power users can set it to "NO" if they want to.

**Comment by anlinde** [comment]
The snippet should work for the crash reporting NSLog message you mentioned, as that message is only shown when the feature is enabled and the app running with the debugger attached.

Which others are showing up and causing you trouble? You could also say don't initialize the whole SDK when running in debug mode, as I assume you don't need the features in thoses cases anyway. Right?

**Comment by anass-b** [comment]
@anlinde Disabling Hockey SDK initialisation in debug mode using a macro perfectly solved my problem. Thanks.
PS: for some reason "disableCrashReporting" was not recognised and throws a compiler error. Maybe I did something wrong ? I'm using version 3.8.5. But that's not necessary because my problem is solved now

**Comment by anlinde** [comment]
My fault, the property is `disableCrashManager` http://hockeyapp.net/help/sdk/ios/3.8.5/Classes/BITHockeyManager.html#//api/name/disableCrashManager
