### ISSUE TITLE
Cocoapods setup has many warnings

### ISSUE THREAD

**Issue by BobDG** [bitstadium/HockeySDK-iOS#242]
I get tons of warnings like these (only copying 3 here) when I use cocoapods for the setup and then build:

warning: (arm64) /Users/Bobdegraaf/Dropbox (Persoonlijk)/GraafICT/Projecten/Template/Storyboard/App/Pods/HockeySDK/HockeySDK-iOS/HockeySDKCrashOnly/HockeySDK.framework/HockeySDK(BITHockeyManager.o) unable to open object file: No such file or directory
warning: (arm64) /Users/Bobdegraaf/Dropbox (Persoonlijk)/GraafICT/Projecten/Template/Storyboard/App/Pods/HockeySDK/HockeySDK-iOS/HockeySDKCrashOnly/HockeySDK.framework/HockeySDK(BITHockeyAppClient.o) unable to open object file: No such file or directory
warning: (arm64) /Users/Bobdegraaf/Dropbox (Persoonlijk)/GraafICT/Projecten/Template/Storyboard/App/Pods/HockeySDK/HockeySDK-iOS/HockeySDKCrashOnly/HockeySDK.framework/HockeySDK(BITCrashMetaData.o) unable to open object file: No such file or directory

**Comment by lumaxis** [comment]
@BobDG Which version of CocoaPods are you using and what does your Podfile look like?

**Comment by BobDG** [comment]
@lumaxis 

I use Objective-C, the cocoapods version = 0.39.0 and this is my podfile:

platform :ios, '8.0'
inhibit_all_warnings!
target "Template" do
pod 'HockeySDK', :subspecs => ['CrashOnlyLib']
end

**Comment by lumaxis** [comment]
Hey @BobDG,

I just tried reproducing this using your exact `Podfile` and also using CocoaPods `0.39.0` with no luck.
From your original post, I'm seeing that your project seems to be located in your Dropbox folder and also that the path name contains parentheses. Both of these have been known to cause trouble with Xcode in the past. 
Could you try moving the project outside of your Dropbox folder and see if the issue persists?

If that doesn't help, I'd suggest you try the usual CocoaPods troubleshooting steps like deleting your `Pods/` folder and `Podfile.lock` and running `pod install` again. 

Should this still not fix the issue, it would be very helpful if you could provide a simple sample project that reproduces the issue and that we could use to inspect and track down the issue.
Thanks for your assistance in figuring this out!

**Comment by BobDG** [comment]
@lumaxis I tried with a new project and indeed I don't have issues there. I think it might have to do something with the fact that sometimes when I run Cocoapods 'pod install' while the project is open I have a duplicate reference to the main project/target in the left-hand navigator. So below the Pods target reference is another reference to the exact same target of the one at the top. Even if I remove it there though I keep seeing these issues.. But I guess it's not the HockeySDK that is doing this :)
