### ISSUE TITLE
BTCrashManager appEnteredForeground not called if startManager called from didFinishLaunchingWithOptions

### ISSUE THREAD

**Issue by galbraithjoseph** [bitstadium/HockeySDK-iOS#246]
appEnteredForeground is not called if startManager is called from didFinishLaunchingWithOptions; this is because during didFinishLaunchingWithOptions (at least on iOS 9.2.1), [[UIApplication sharedApplication] applicationState] is UIApplicationStateInactive and so the check at the bottom of startManager does not pass.

The notification never fires either, until the app is backgrounded and then made active again.

This causes app not terminating cleanly detection to not work unless the user backgrounds the app at least once.

**Comment by TroubleMakerBen** [comment]
I'm closing this issue as it's almost 2 years old. Please feel free if you still have that issue.

Best,
Benjamin
