### ISSUE TITLE
Spaces in version number not escaped in urls

### ISSUE THREAD

**Issue by mtoon** [bitstadium/HockeySDK-iOS#249]
If you have a space in your CFBundleIdentifier, the https calls fail with a 
[HockeySDK] -[BITUpdateManager reportError:]/91 ERROR: unsupported URL

Looking at the code, it seems this might be a simple fix by adding space as one of the encodable characters in BITHockeyHelper::bit_URLEncodedString

We found this after upgrading to 3.8.5 from 3.6.2 and the usage stats were no longer updating for the builds.  Putting hockey in debug mode (very helpful BTW!), provided the URL it was trying to send.  Pasting that into a browser immediately worked.

Our build numbers look something like this (last part is commit hash):
254 {ProjectName, boc1ob1}

which are getting encoded as:
app_version=254 {ProjectName%2C b0c10b1}

Which makes sense why the URL would fail.

**Comment by lumaxis** [comment]
Thanks @mtoon for finding this! I already started looking into this and am working on a fix. I'll let you know once it's merged.
I'm also glad you found the debug mode helpful 🙂 We're working on an enhanced version with a more configurable debug log in #244, in case you want to take an early look.

**Comment by mtoon** [comment]
@lumaxis Thanks!  Just created a PR for this.. we need the curly braces as well if that's ok.  Here's the PR:
https://github.com/bitstadium/HockeySDK-iOS/pull/250

Thanks again!

**Comment by lumaxis** [comment]
Just a quick note: According to [Apple's documentation](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364), a bundle version 
> […] should only contain numeric (0-9) and period (.) characters.

So you might still want to look into changing your build system and the string as it's not guaranteed that all of Apple's systems will support it.

**Comment by mtoon** [comment]
Thanks for the note.  For production (app store builds) we adhere to that.. It's only the beta-team builds that have the special Project, Hash build id.  Thanks again!
