### ISSUE TITLE
HockeySDKResources.bundle is missing

### ISSUE THREAD

**Issue by Ji11erBug** [bitstadium/HockeySDK-iOS#252]
I am using HockeySDK Crash Only. I connect the library as discarded in the instruction. I guess HockeySDKResources are not needed for Crash Only functionality, but why framework still produces warnings, can it be removed?

**Comment by anlinde** [comment]
By default the resource bundle is needed, as the SDK shows an alert on the next startup asking the user if they agree to send the crash reports.

If you setup the SDK to send crashes without asking your users, you don't need the resource bundle.

**Comment by Ji11erBug** [comment]
Ok. I understand you. So why HockeySDKResources.bundle is only in HockeySDK.embeddedframework subfolder and missing for HockeySDKCrashOnly and HockeySDKCrashOnlyExtension

**Comment by anlinde** [comment]
With Extensions the bundle is not needed, as alerts are not allowed in Extensions and the SDK automatically turns on auto-sending.

In general the SDK turns on auto-sending of crash reports if it can't find the bundle but shows the warning to make you aware of this. If you want the alerts, you can copy the bundle from the embedded framework.

**Comment by Ji11erBug** [comment]
Ok. Thank you. I think issue can be closed.
