### ISSUE TITLE
Manual update impossible, if updateSetting != BITUpdateCheckManually

### ISSUE THREAD

**Issue by RomanTruba** [bitstadium/HockeySDK-iOS#256]
I'm using BITUpdateManager with update settings equal to BITUpdateCheckDaily.
I want to add possibility for checking for update manually in any moment, but seems like calling `[[BITHockeyManager sharedHockeyManager].updateManager checkForUpdate];` do nothing.

Version 3.8.2

**Comment by anlinde** [comment]
That is most likely because there was already an update check on that day at the time the app started or got into focus.

Why don't you use set `updateSetting` to `BITUpdateCheckManually` and call `checkForUpdate` every time you want?

**Comment by Dreddik** [comment]
Because I don't want to store a daily update time by myself.
I believed `checkForUpdate` method would force update, ignoring daily update flags.
That's seems like undefined or undocumented behavior.

**Comment by anlinde** [comment]
`BITUpdateCheckDaily` really means daily once and it will not make sure not to call it more than once on a day. That's how it is implemented and was meant to be from our end.

So if you want it to behave differently, you need to set it to `BITUpdateCheckManually` and call it yourself the way you want it to do. In that case `checkForUpdate` will not block any calls and process it whenever you call it.

**Comment by Dreddik** [comment]
And what if I will switch setting to `BITUpdateCheckManually` before calling `checkForUpdate `, and set back to `BITUpdateCheckDaily` after? As I understand, it shouldn't affect `lastCheck` field, and then SDK will continue checking for update daily. Correct?

**Comment by anlinde** [comment]
This might work, but I can't guarantee it will always work like this.

Could you describe the scenario you have why you want it to behave like that and how you would trigger additional update checks?

**Comment by Dreddik** [comment]
For example, some days we might upload 2-3 build a day. After upload I say to my team: "I didn't want to worry you with email, because it's minor update, but if you want to update right now, just press the button in "Settings".

I just switched to `BITUpdateCheckDaily` from `BITUpdateCheckStartup`, because startup checks is too frequent for many people. And to leave possibility for quick in-app update, I added update button.
And then I realized `checkForUpdate` don't work as I expected.

**Comment by anlinde** [comment]
I understand, thanks for explaining. Please let me know if your idea works. I'll put it on our list and see what we can do in a future update to make this easier.

**Comment by joshbuhler** [comment]
We're in a similar situation to @Dreddik - my team often has multiple builds each day, so we've changed our update checks to be `BITUpdateCheckDaily`. However, there are times where we'd like a tester to be able to hit a "Check for Updates" button and do a manual check.

Right now, were doing something like this, and it appears to be working:

```
    BITHockeyManager *hockeyMan = [BITHockeyManager sharedHockeyManager];
    hockeyMan.updateManager.updateSetting = BITUpdateCheckManually;
    [hockeyMan.updateManager checkForUpdate];
    hockeyMan.updateManager.updateSetting = BITUpdateCheckDaily;
```

For most of our testing, a daily check is sufficient, but there are enough times where having the ability to do a manual check would be nice. Even if the `checkForUpdate` behavior doesn't change, maybe there should be an update to the docs explaining that this method only works with the update setting is set to `BITUpdateCheckManually`.
