### ISSUE TITLE
Just wondering when will be new release

### ISSUE THREAD

**Issue by dingtianran** [bitstadium/HockeySDK-iOS#258]
There is no new official release build for iOS since last October, almost half a year.

**Comment by anlinde** [comment]
We are planning on providing an update very soon.

Best,
Andreas

**Comment by dingtianran** [comment]
Hi @anlinde, thanks.
Nothing particular, just curious.
Take your time.

**Comment by lumaxis** [comment]
Here we go: https://github.com/bitstadium/HockeySDK-iOS/releases/tag/3.8.6
:rocket:
