### ISSUE TITLE
Unable to build app if HockeySDK is loaded as pod with use_frameworks!

### ISSUE THREAD

**Issue by dral3x** [bitstadium/HockeySDK-iOS#265]
Hello there,

I'm updating our app and i'm not able to building it anymore when I started migrating all libraries as dynamic framework.
The issue reported is during `Copy Pods Resources` phase

```
PhaseScriptExecution 📦\ Copy\ Pods\ Resources /Users/alex/Library/Developer/Xcode/DerivedData/SPKApp-feiiwlszncfvhpetlgllbfrpshmr/Build/Intermediates/SPKApp.build/Debug-iphonesimulator/SPKApp.build/Script-A8A602A7D45C28B2D256C98C.sh
    cd /Users/alex/Desktop/test/SPKApp
    /bin/sh -c /Users/alex/Library/Developer/Xcode/DerivedData/SPKApp-feiiwlszncfvhpetlgllbfrpshmr/Build/Intermediates/SPKApp.build/Debug-iphonesimulator/SPKApp.build/Script-A8A602A7D45C28B2D256C98C.sh

error: Resource "/Users/alex/Library/Developer/Xcode/DerivedData/SPKApp-feiiwlszncfvhpetlgllbfrpshmr/Build/Products/Debug-iphonesimulator/HockeySDK/HockeySDKResources.bundle" not found. Run 'pod install' to update the copy resources script.
```

The folder `HockeySDK` inside `DerivedData/.../Debug-iphonesimulator` does not exist. The bundle is inside the `Debug-iphonesimulator` folder directly.

To reproduce it, just create an empty project with this `Podfile`

``` 
platform :ios, '8.0'
use_frameworks!

target 'SPKApp' do
    pod 'HockeySDK', '3.8.5'    
end
```

Can I work around this issue? Any help is appreciated!
I cannot remove the `use_framework!` directive because I will be load also swift libraries.

Thanks

**Comment by dral3x** [comment]
The problems seams to be related to the latest version of cocoapods (1.0.0.beta5)

**Comment by lumaxis** [comment]
Hey @dral3x! Yes, this is an issue with the latest CocoaPods prerelease version. Using the latest table `0.39.0` or `1.0.0.beta.3` still works though.
This is being tracked in this issue: https://github.com/CocoaPods/CocoaPods/issues/4963

**Comment by dral3x** [comment]
Thanks @lumaxis !

As workaround for the moment, I can also use `Hockey-Source`.
Just so you know

**Comment by lumaxis** [comment]
Ah, right. I mentioned that to somebody else yesterday too but forgot today :see_no_evil: 
Another trick that might make some lives easier: You can still use the older version of the CocoaPods gem by calling it like this `pod _0.39.0_ install`

**Comment by dral3x** [comment]
I already migrated all my Podfile to the new keywords etc so I prefer to use a different workaround but thanks! That's another great hint!

**Comment by lumaxis** [comment]
Just a quick FYI: A new version of CocoaPods that fixes this issue has just been released: https://github.com/CocoaPods/CocoaPods/releases/tag/1.0.0.beta.6

**Comment by gereons** [comment]
This just resurfaced on my CI box after updating to Cocoapods 1.0. Reverting to 0.39.0 solves the issue, unfortunately `Hockey-Source` doesn't even compile for me.

**Comment by lumaxis** [comment]
@gereons Just to clarify, with which pod are you seeing this issue on your CI box, `HockeySDK` or `HockeySDK-Source`? The former works fine for me, I'm investigating the issue with the latter.

**Comment by gereons** [comment]
I saw the "HockeySDKResources.bundle not found" problem as described by @dral3x
Tried using HockeySDK-Source instead, couldn't compile because some private header files couldn't be #imported.
Reverted back to CP 0.39.0 and using HockeySDK since I can't currently spend time on the investigation, unfortunately.

**Comment by lumaxis** [comment]
Hm, weird. I'm using this Podfile:
```ruby
use_frameworks!

target 'CocoaPods-Frameworks' do
	pod 'HockeySDK'
end
```
and `pod install` with CocoaPods 1.0 works without any issues.

**Comment by gereons** [comment]
The problem does not occur at `pod install` time, but while building, during the `Copy Pods Resources` phase.

**Comment by lumaxis** [comment]
Yes, sorry forgot to mention that it also builds fine for me after running `pod install`. Do you also have this problem when building locally or does it only occur on the CI machine? Do you have your `Pods` directory checked into source control?

**Comment by gereons** [comment]
Weirdly enough, this only happened on the CI machine. The Pods directory is not versioned, but clearing it and all cocoapods caches didn't help.

**Comment by lumaxis** [comment]
@gereons Unfortunately without any further information or steps how to reproduce this I can't really help with this :/
FWIW though, the issue with `HockeySDK-Source` should be fixed now, can you try that again?

**Comment by gereons** [comment]
@lumaxis Understandable, this is most likely a cocoapods issue anyway. I just wanted to let you guys know.
I'll see if I can investigate more soon, when I can afford to not have a running Jenkins for a few days.

And thanks for fixing `HockeySDK-Source`, that works now.

**Comment by lumaxis** [comment]
Yep, if you ever find steps to repro this, please do share :)
Thanks already for letting us know 👍

**Comment by tutipeti** [comment]
For the record: after digging through a billion issues on the CocoaPods GitHub repo I found this one: https://github.com/CocoaPods/CocoaPods/issues/5358 which might explain why the builds are failing on CI (like it did for me now).
