### ISSUE TITLE
Usage time statistics not sent

### ISSUE THREAD

**Issue by gershwin88** [bitstadium/HockeySDK-iOS#268]
When updateSetting is set to BITUpdateCheckManually and checkForUpdate is never called. Usage statistics are never sent to the server.

This comes up because I do not want the user to be prompted to update when there is a newer version but do want to see user statistics.

It looks like this is do to the fact that usage statistics are sent in the request to checkForUpdate in BitUpdateManager, but since I have the app set to never check for updates usage statistics are never sent

**Comment by anlinde** [comment]
Yes, this is by design. With the new User Metrics feature coming up in our Preseason program this will be separated and also working for store releases. See http://hockeyapp.net/preseason/

**Comment by gershwin88** [comment]
Thanks for the reply, I'll check out preseason.
