### ISSUE TITLE
Difficult to recover from error during identifyWithCompletion

### ISSUE THREAD

**Issue by eliburke** [bitstadium/HockeySDK-iOS#273]
In our app, I don't need to authenticate the user, I just want them to self-identify with a valid email address. As long as the email address is correct, everything works. However, if the user enters an invalid email address ... it's pretty much game over without restarting the app. 

The problem is that on failure (say an invalid email is entered), BITAuthenticationViewController calls completion (NO, error) but does NOT dismiss itself.
1) At this point, it is impossible to call identifyWithCompletion again because BITAuthenticatior checks to see if it is already visible. 
2) If the user corrects the invalid email address and clicks Done, the BITAuthenticationViewController DOES dismiss itself, but the completion block is not called, so it is impossible to use it for flow control. 
3) If the user does not correct the email address and clicks Done, the email address is checked but again the completion block is not called.
4) After multiple failed attempts, I would repeatedly see the text field losing first responder status (or something) and the keyboard becomes permanently dismissed

I was ultimately able to semi-recover by capturing the BITAuthenticationViewController in the delegate method authenticator:willShowAuthenticationController, and calling dismissViewController on it directly. However, it does not clear the internal _authenticationController property, so identifyWithCompletion can't be called again.

I think that to fix this you need to tweak the completion block so that it is called once the user enters a valid email address, or expose the private method dismissAuthenticationControllerAnimated so that we can manually take care of it.

**Comment by lumaxis** [comment]
As it happens, I am just looking into a problem very closely related to this one today.
I'll make sure to also cover your use case and see that we provide a fix soon :ok_hand:

**Comment by TroubleMakerBen** [comment]
I'm closing this issue as it's almost 2 years old. Please feel free if you still have that issue.

Best,
Benjamin
