### ISSUE TITLE
iOS HockeySDK saves project git data to NSUserDefaults

### ISSUE THREAD

**Issue by milanstevanovic** [bitstadium/HockeySDK-iOS#282]
I have encountered a very strange problem while working with latest version of HockeySDK for iOS.
On a project that I'm working on, client hired a pen-testing company.
They found a potential security issue that we traced back to the HockeySDK.
When we setup the HockeySDK it fills the NSUserDefaults plist file in the iPhone's memory (Library/Preferences/com.<organization>.<app>.plist) with some data that shouldn't be there, namely data about our git repo under the key "BITUpdateArrayOfLastCheck" in base64. The data contains all our commits, and links to the repositories.
Did someone else encounter this problem before, and do you know how to solve it, and what is the reason for this?
I must imply that this does not happen when we don't use HockeySDK, so by trial and error I'm pretty sure that the HockeySDK is causing this.

**Comment by lumaxis** [comment]
@milanstevanovic I'm not entirely sure I can follow. What kind of data has been found there? Can you describe in more detail what "data about our git repo" means?
In general, the data saved under the `BITUpdateArrayOfLastCheck` key is a small cache of the versions of your app that the SDK received through the HockeyApp API so it wouldn't be surprising if the data found contains your last versions and the related metadata.

**Comment by milanstevanovic** [comment]
@lumaxis  Sorry for not being clear. Under "data" I meant it contains complete list of all commits, for example "Commit 1: Merged branch X with branch Y, Commit 2: Fixed bug for ticket XXX", and there are also links to the repo in some commits, so this is considered a possible security risk. I tried to find where and why is this happening but I can't seem to locate the problem. It basically copies the whole log of the git repo into the "BITUpdateArrayOfLastCheck" key's value.

**Comment by milanstevanovic** [comment]
@lumaxis It copies the whole git log under the "BITUpdateArrayOfLastCheck" key. For example:
"
[Bug] Fixed bug for ticket 453
[Merge] Merged branch X with branch Y
"
So basically the list of all the commits, same as it is display in SourceTree for example.
Some of our commits contain links to the repo, so client is considering this a security flaw.
I tried to figure out why is this happening but i can't seem to get to the core of the problem.
We are initializing HockeySDK as follows:

`
[[BITHockeyManager sharedHockeyManager] configureWithIdentifier:@"a743494e3b42465b8177fb6525743b40"];
    [[BITHockeyManager sharedHockeyManager] setDelegate:self];
    [[BITHockeyManager sharedHockeyManager] startManager];
    [[BITHockeyManager sharedHockeyManager].authenticator authenticateInstallation];
`

and we are implementing delegate methods:

- (NSString *)userIDForHockeyManager:(BITHockeyManager *)hockeyManager componentManager:(BITHockeyBaseManager *)componentManager;

- (NSString *)userNameForHockeyManager:(BITHockeyManager *)hockeyManager componentManager:(BITHockeyBaseManager *)componentManager;

- (NSString *)userEmailForHockeyManager:(BITHockeyManager *)hockeyManager componentManager:(BITHockeyBaseManager *)componentManager;

**Comment by lumaxis** [comment]
Thanks for the additional info @milanstevanovic, we'll investigate!
Would you mind additionally opening a support request at https://support.hockeyapp.net with your App ID so we can take a closer look?

**Comment by anlinde** [comment]
@milanstevanovic Do you add your git commits into the release notes?

**Comment by milanstevanovic** [comment]
@lumaxis Sure, I created the issue, thanks for the fast replies
@anlinde Yes, and we have the merge in release notes, for example: Merge branch 'master' of https://git.<our-website>.com. Is it possible to disable/remove this for old commits?

**Comment by anlinde** [comment]
@milanstevanovic: that's the reason, the SDK caches the update information including the release notes for the Update UI. So this only happens for your beta versions and will never happen in the App Store as the whole functionality is automatically disabled in that environment.

**Comment by milanstevanovic** [comment]
@anlinde @lumaxis 
That's really cool, it makes my job a lot easier.
Really professional and fast support, thank you guys again for helping me! 👍
