### ISSUE TITLE
Conflict with PINRemoteImage (probably other networking libraries)

### ISSUE THREAD

**Issue by taher-mosbah** [bitstadium/HockeySDK-iOS#283]
Please see my issue here ::
https://github.com/pinterest/PINRemoteImage/issues/192

Regards

**Comment by anlinde** [comment]
Hi @taher-mosbah 

I am not sure I understand what the issue is? Is there a compiler or linker error you get? Could you provide a sample project that shows the issue?

Best,
Andreas

**Comment by lumaxis** [comment]
@taher-mosbah Unfortunately, we have no clear idea what the issue is and have also not heard any similar issues. I'll close this for now, please feel free to re-open with more info at any time!
