### ISSUE TITLE
Unable to read the license file

### ISSUE THREAD

**Issue by ccombes** [bitstadium/HockeySDK-iOS#284]
Using the latest version 3.8.6 and I see the following error:
[!] Unable to read the license file `<path>/Pods/HockeySDK/HockeySDK-iOS/LICENSE` for the spec `HockeySDK (3.8.6)`

It appears this file has moved.

**Comment by lumaxis** [comment]
Unfortunately, I cannot reproduce this locally.
Which CocoaPods version are you using? I tried both `0.39.0` and `1.0.0.beta.8`.
Also, would you mind posting the contents of your Podfile?

**Comment by ccombes** [comment]
I'm sorry.  It appears it is a path issue on our end.  I will update this post shortly.

**Comment by ccombes** [comment]
I'm up and running again.  Rather than post a lengthy explanation I will simply say that I updated our podfile as per the readme.  I appreciate your responding.

**Comment by lumaxis** [comment]
Sure, no problem :) Glad you got it working again!
