### ISSUE TITLE
Cannot unset userID and userName anymore

### ISSUE THREAD

**Issue by fluidsonic** [bitstadium/HockeySDK-iOS#294]
We set `BITHockeyManager`'s `userID` and `userName` properties when the user is signed in.
Once the user signs out, we unset the properties by setting them to `nil`. In that case the SDK falls back to its own generated user ID.

With a recent update of your SDK, `userID` and `userName` have been annotated **non-nullable**, which effectively prevents us from unsetting these values. An empty string will cause a different behavior than setting the values to `nil`.

How is a log-out supposed to be handled now?

```
private func identifyUser() {
	if let user = context.userManager.authenticatedUser {
		hockey.userID = user.id
		hockey.userName = user.name
	}
	else {
		hockey.userID = nil   // error: Nil cannot be assigned to type 'String'
		hockey.userName = nil // error: Nil cannot be assigned to type 'String'
	}
}
```

**Comment by lumaxis** [comment]
Hey @fluidsonic! As you can see, I just fixed this in https://github.com/bitstadium/HockeySDK-iOS/commit/0ba22989342409d757a3d8b3150f05a28c1b1f9e and it will be available in the next release.

>An empty string will cause a different behavior than setting the values to nil.
What different behavior do you see? How are you using the "log-out"?

**Comment by fluidsonic** [comment]
Thanks, good to know!

I derive the differing behavior from the SDK's sources since there's no documentation about what happens when I set `userID` to an empty string.

[BITCrashManager.m, line 635](https://github.com/bitstadium/HockeySDK-iOS/blob/94d46b3d0af1af9e574a07f6deb94b0b2868d819/Classes/BITCrashManager.m#L635) for example will behave different when the `userID` is `nil` (unset) or an empty string.

When our users log out, we want to unset all user info in the SDK. As per documentation we just need to set `userID` and `userName` to `nil`:

> To delete the value from the keychain set the value to `nil`.

**Comment by lumaxis** [comment]
You are right that there are indeed cases where the SDK differs when `userID', etc. are `nil` but these are only present in the `BITFeedbackManager` class, like [here](https://github.com/bitstadium/HockeySDK-iOS/blob/94d46b3d0af1af9e574a07f6deb94b0b2868d819/Classes/BITFeedbackManager.m#L371-L375) for example.

The example you mentioned is actually not problematic as it defaults to empty string [a few lines later](https://github.com/bitstadium/HockeySDK-iOS/blob/94d46b3d0af1af9e574a07f6deb94b0b2868d819/Classes/BITCrashManager.m#L645) anyway.

Setting an empty string should be a functioning workaround to remove all user data for the time being.

**Comment by fluidsonic** [comment]
Haut it overwrites the user ID set a few lines earlier.

Anyway we'll just stick with 3.8.6 until this is fixed :)
