### ISSUE TITLE
Using Feedback Manager w/ AlertController on screen moves AlertController

### ISSUE THREAD

**Issue by gabek** [bitstadium/HockeySDK-iOS#300]
If you present the feedback manager (via taking a screenshot) while an iOS AlertController is on the screen, the AlertController is moved when dismissing the feedback manager.

Is this something anybody has seen before?

![image_0](https://cloud.githubusercontent.com/assets/414923/15839867/e078b98e-2bfa-11e6-8ed7-cb250ee47322.jpg)

**Comment by erinstandley** [comment]
What I've noticed is:

1. take screenshot
2. AlertController moves
3. feedback manager appears
4. close feedback manager (via `Cancel` or `Send`)
5. AlertController remains in the arrangement you see in @gabek's comment

**Comment by erinstandley** [comment]
Still having the same issue, but the alert isn't repositioned.

![img_3087](https://cloud.githubusercontent.com/assets/16926315/18369216/52ed6794-75d9-11e6-989e-d14c4244b076.PNG)

**Comment by gabek** [comment]
I learned this is actually what happens any time you `present` a new UIViewController from a `UIAlertController`.  It's not specific to Hockeyapp.
