### ISSUE TITLE
App Hangs when MetricsManager is disabled and exception is thrown

### ISSUE THREAD

**Issue by DangMH** [bitstadium/HockeySDK-iOS#301]
### Repro Project
[TestHockeyApp.NativeiOS.zip](https://github.com/bitstadium/HockeySDK-iOS/files/301795/TestHockeyApp.NativeiOS.zip)

### Repro Steps
1. Start app
2. Press 'Throw Exception'
3. Verify app hangs

### Notes
Occurs when MetricsManager is disabled before the manager is started:
```
    [[BITHockeyManager sharedHockeyManager] configureWithIdentifier:@"Your-App-Id"];
    [[BITHockeyManager sharedHockeyManager] setDisableMetricsManager:YES];
    [[BITHockeyManager sharedHockeyManager] startManager];
```

**Comment by chrwend** [comment]
Fixed via #302
