### ISSUE TITLE
BITUpdateViewController—tableView:cellForRowAtIndexPath: can return nil

### ISSUE THREAD

**Issue by philippec** [bitstadium/HockeySDK-iOS#305]
In BITUpdateViewController, the delegate method tableView:cellForRowAtIndexPath: has a code path that can return nil. The method is now marked as expecting a non-null value, so the static analyzer reports: 

HockeySDK/Classes/BITUpdateViewController.m:499:3: warning: Null is returned from a method that is expected to return a non-null value

**Comment by TroubleMakerBen** [comment]
Fixed with 4.1.2
