### ISSUE TITLE
BITFeedbackListViewController—previewController:previewItemAtIndex: can return nil

### ISSUE THREAD

**Issue by philippec** [bitstadium/HockeySDK-iOS#306]
In BITFeedbackListViewController, the delegate method previewController:previewItemAtIndex: has a code path that can return nil. The method is now marked as expecting a non-null value, so the static analyzer reports:

HockeySDK/Classes/BITFeedbackListViewController.m:1014:3: warning: Null is returned from a method that is expected to return a non-null value

**Comment by TroubleMakerBen** [comment]
Fixed as of 4.1.2
