### ISSUE TITLE
iOS library compatibility with Apple IPv6 changes. [TL;DR: Yes, HockeySDK-iOS is compatible]

### ISSUE THREAD

**Issue by Muesly** [bitstadium/HockeySDK-iOS#307]
Is the HockeySDK using IPv6 only as per: http://appleinsider.com/articles/16/05/04/apple-says-all-apps-must-support-ipv6-only-networking-by-june ?

If so, do I need to conform to a particular version number?

**Comment by lumaxis** [comment]
Hi @Muesly! Yes, HockeySDK is completely compatible to IPv6-only networks as we only use high-level networking APIs such as `NSURLSession` and have no hardcoded IPv4 addresses in our code.
Although this has been the case for quite some time, please be aware that we only officially support the current stable version so make sure to update to `4.0.1` if you haven't already :)

**Comment by TroubleMakerBen** [comment]
Leaving this open for better visibility for a couple more weeks.

**Comment by TroubleMakerBen** [comment]
Just to make sure this is at the top of the list of issues.

**Comment by TroubleMakerBen** [comment]
Closing this as we've had it open for a couple of extra months to make sure everyone had a chance to read this.
