### ISSUE TITLE
Headers are marked as private - causes issues when integrating the SDK as sources

### ISSUE THREAD

**Issue by blach** [bitstadium/HockeySDK-iOS#309]
The files BITHockeyLoggerPrivate.h and BITChannelPrivate.h are marked as private in the Xcode project.

When archiving my app, these header files are put into the "Private Headers Folder Path" which by default is /usr/local/include.

The headers should be marked as "Project", not "Private". "Private" headers are exported to the build product.

<img width="409" alt="bildschirmfoto 2016-07-06 um 21 47 31" src="https://cloud.githubusercontent.com/assets/1008289/16632284/ba5f4778-43c3-11e6-92e5-a0ec7c367e31.png">

Here is how that looks in my app archive: 
<img width="307" alt="bildschirmfoto 2016-07-06 um 21 50 47" src="https://cloud.githubusercontent.com/assets/1008289/16632285/bc33fabc-43c3-11e6-8422-a03cd64e971f.png">

Xcode doesn't recognize the archive as an iOS app, so I cannot upload it to the App Store.

If I change the header to "Project", everything works as expected.

**Comment by lumaxis** [comment]
Thanks for catching this!
