### ISSUE TITLE
Sending crash report 

### ISSUE THREAD

**Issue by DiegoV71** [bitstadium/HockeySDK-iOS#314]
Hi, I include this component in project and code in appdelegate
```C#
var manager = BITHockeyManager.SharedHockeyManager;
manager.Configure("*MyAppID*");
manager.CrashManager.CrashManagerStatus = BITCrashManagerStatus.AutoSend;
manager.StartManager();
```
but reports about my` throw new Exception("message")` not send to service; help me please;

**Comment by TroubleMakerBen** [comment]
Hello @DiegoV71,

Thanks for getting in touch.
Although your integration code looks fine, it's pretty hard to see from these 5 lines of code what's going on. Please open a support ticket on [support.hockeyapp.net](http://support.hockeyapp.net) so we can have a closer look, e.g. share some code non-publicly.

Some things I can think of without knowing more:
* Does your exception crash the app? If you're handling the exception and not crash the app yourself, our SDK won't report the exception. You can find more about what kinds of crashes our SDK can detect [in our knowledgebase](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/which-types-of-crashes-can-be-collected-on-ios-and-os-x).
* Do you use any other crash reporting sdks in your app? On iOS, it's not possible to have more than one exception handler.

Something you can do yourself is to [enable debug logging](https://github.com/bitstadium/HockeySDK-iOS#debug) and check in the console of you see error messages by the SDK.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
Just found out that you're seeing issues with our Xamarin SDK and have opened a support request. Closing this issue.
