### ISSUE TITLE
Update PLCrashReporter to 1.3

### ISSUE THREAD

**Issue by vox-humana** [bitstadium/HockeySDK-iOS#315]
Current version of PLCrashReporter (actually 1.3 is still in development I suppose) has a great feature for collecting handled exceptions (asserts)
[PLCR-459](https://opensource.plausible.coop/bugs/browse/PLCR-459) `generateLiveReportWithThread:thread:exception:` method , which could be very handy.

**Comment by anlinde** [comment]
This is already on our to do list to add, but we don't have an ETA when this will happen. Our Backend is not ready for this yet.

**Comment by vox-humana** [comment]
@anlinde thank you for the quick response.
Are you talking about upgrading PLCrashReporter framework or full support 'handled/silent exceptions' feature in HockeySDK? We look forward to getting this feature in SDK 😄

**Comment by anlinde** [comment]
We plan to add support for handled Errors, yes.
