### ISSUE TITLE
Carthage and Photo Library usage

### ISSUE THREAD

**Issue by justin** [bitstadium/HockeySDK-iOS#350]
We got bit by the NSPhotoLibraryUsageDescription exception when uploading a build to iTunes. 

Is it possible to either include that `NSPhotoLibraryUsageDescription` key as part of your framework or just ship a Carthage version without that functionality? We use Hockey solely for the crash reporting. I'd rather not have to localize and manage strings for functionality we aren't using just because it's bundled by a third-party library.

**Comment by anlinde** [comment]
Regarding defining `NSPhotoLibraryUsageDescription` as part of the SDK: this is technically not possible. You need to add this to your apps `Info.plist`, there is no way this can be done by the SDK, also no way to do it at runtime as this would break signing.

**Comment by TroubleMakerBen** [comment]
Closing this issue.
