### ISSUE TITLE
Xcode Error: Invalid bitcode version (Producer: '800.0.24.1_0' Reader: '703.0.31_0') 

### ISSUE THREAD

**Issue by gemmakbarlow** [bitstadium/HockeySDK-iOS#358]
After updating to the 4.1.2 version of the HockeyApp SDK causes the following error when archiving our project for distribution (on Xcode 7.3.1 - compiled against Swift 2.3)- `Xcode Error: Invalid bitcode version (Producer: '800.0.24.1_0' Reader: '703.0.31_0')`

I've reverted back to 4.1.1 now, and can build happily. 

Feels related to https://github.com/bitstadium/HockeySDK-iOS/pull/344; at the very least, would be good to add some notes to the README about Xcode compatibility with each version.

**Comment by TroubleMakerBen** [comment]
Hey Gemma,

thanks for getting in touch. You're right, 4.1.2 was compiled using Xcode 8 and if you are using bitcode, it requires Xcode 8.
We're discussing releasing 4.1.3 of the SDK to bring back compatibility with Xcode 7.3.1.

Sorry for inconvenience this causes, I'll update the issue as soon as I have news for you.

Best,
Benny

**Comment by gemmakbarlow** [comment]
No worries - and thanks for the update. Look forward to hearing back.

- G

**Comment by TroubleMakerBen** [comment]
Hey @gemmakbarlow 

We've discussed Xcode 7.3.1 support and we chose not to release a new version of the SDK to bring back support for 7.3.1 for now as Apple will stop to allow submissions with Xcode 7.3.1 in the not too far future. 
Sorry for the inconvenience this causes you.

Best,
Benny

**Comment by gemmakbarlow** [comment]
No worries - might recommend adding a note to the README about comptability however.

> ...at the very least, would be good to add some notes to the README about Xcode compatibility with each version...

**Comment by TroubleMakerBen** [comment]
Will do that =)
