### ISSUE TITLE
Xcode Log

### ISSUE THREAD

**Issue by BaiCanLin** [bitstadium/HockeySDK-iOS#361]
![image](https://cloud.githubusercontent.com/assets/8268339/19716695/be1ebfd2-9b8f-11e6-94fb-0a134b019637.png)

objc[4387]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x106270998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x105ffed38). One of the two will be used. Which one is undefined.

**Comment by TroubleMakerBen** [comment]
Hi @BaiCanLin 

Thanks for getting in touch. I just googled your issue and found several links that explain the issue (e.g. [Apple Developer Forum](https://forums.developer.apple.com/thread/63254) or [this post on SO](http://stackoverflow.com/questions/39520499/class-plbuildversion-is-implemented-in-both-frameworks) and as on of the answers on Stackoverflow suggests, this might be a bug on Apple's side.  And HockeySDK-iOS Indeed references both the asset library and the photos framework.
That said, I tried to reproduce the issue and I can't repro the warning. 

I'd like to help you, but I need more info for this:
* Which version of our SDK are you using?
* How are you integrating the SDK?
* Which Xcode version are you using?
* Do you see the warning showing coming up for specific devices/simulators?

If you're not using 4.1.2 of our SDK, please upgrade the SDK (also have a look at our readme regarding iOS 10 and Xcode 8). If you continue to see the warning, would you please provide a demo project that would allow me to reproduce the issue?

Best,
Benny

**Comment by TroubleMakerBen** [comment]
Closing this as I haven't heard from you.
Feel free to get in touch and I'll open the issue again.

Benjamin
