### ISSUE TITLE
Pressing 'show' in Update Alert does not show Update view on iOS

### ISSUE THREAD

**Issue by q231950** [bitstadium/HockeySDK-iOS#362]
We have observed for some of our employees and even ourselves it happens that 'sometimes' the `show` button of the Update Alert does not present the Update Screen. 
Once this happened the Alert will never show up again after sending the App to background and coming to foreground again. Only after killing the App, the Alert will potentially show up again. 

It seems to occur randomly on all kind of devices. 

Is this a known issue when having a certain view hierarchy in the App?

Hockey SDK is 4.0.2.

**Comment by TroubleMakerBen** [comment]
Hi @q231950,

thanks for getting in touch. I haven't heard of this before. Is there an iOS version where it's happening more often?
Have you customized in-app-updates?

I would love to hunt this one down.

Best,
Benny

**Comment by q231950** [comment]
Hi @TroubleMakerBen,

thanks for the quick reply. We first had the impression that it would happen more often on slower devices, but then we noticed it on fast ones as well.

Devices where I saw it myself were all on iOS10.x, I can check on a iOS9.x today. It seems to be random. 

We haven't customised the Alert, we do the setup in the following order during `application:didFinishLaunchingWithOptions:`:

`[BITHockeyManager.sharedHockeyManager configureWithIdentifier:identifier];`
`[[BITHockeyManager sharedHockeyManager].crashManager setCrashManagerStatus:BITCrashManagerStatusAutoSend];`
`BITHockeyManager.sharedHockeyManager.userID = userID;`
`[BITHockeyManager.sharedHockeyManager startManager];`
`[BITHockeyManager.sharedHockeyManager.authenticator authenticateInstallation];`

Best,
Kim

**Comment by q231950** [comment]
Hi @TroubleMakerBen 

I just checked on one iOS 9.x device and couldn't reproduce it there. As the issue occurs randomly I still wouldn't rule out iOS 9, though.

If there's anything that comes to your mind just by looking at the order of our calls, please let me know. 

Thank you and have a great day
kim

**Comment by TroubleMakerBen** [comment]
Hi @q231950 

Thanks for checking this on iOS 9.
Your setup-code looks fine. I'll try to poke around this week, hopefully tomorrow. Maybe I can repro the issue here.

I appreciate your patience!

Benny

**Comment by TroubleMakerBen** [comment]
Hey @q231950,

It's been a while and I have done testing. I couldn't repro this issue at all on 10.1.1 and 9.3.5.
How's the state of things? I guess you're still seeing this issue?

Best,
Benjamin

**Comment by q231950** [comment]
@TroubleMakerBen 

Hi there, sorry for the late reply. A colleague of mine just came to me after it didn't work for him twice (iPhone 6s 10.1.1). When we did it together it worked, it's like ✨

-> tap on show -> nothing happens (only alert goes away)

Thank you
kim

**Comment by q231950** [comment]
Can't reproduce any more. Thanks for your efforts 👏

**Comment by TroubleMakerBen** [comment]
Oh, you are welcome. I'm really glad it doesn't happen anymore.
Let me know in case anything comes up and thanks for using HockeyApp!
