### ISSUE TITLE
Xcode 8.1 - 'bundle format unrecognized, invalid, or unsuitable'

### ISSUE THREAD

**Issue by Stengo** [bitstadium/HockeySDK-iOS#363]
Building in Xcode 8.1 raises the error:
`HockeySDKResources.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1`

HockeySDK version is 4.1.2 (via CocoaPods as a static library)

**Comment by TroubleMakerBen** [comment]
Hi @Stengo,

I just tried to reproduce the issue with yesterday's Xcode build – Xcode 8.1 (8B62) – and Cocoapods 1.1.1. I don't see the issue that you are seeing, integration and building works fine for me.
Can you check the version of your Cocoapods installation and remove HockeySDK from your app and add it back? Other than that, if you continue to see the issue, can you setup a new app with one of Xcode's templates and integrate the SDK? If this works, there is something off with your project setup.
Independently from that, feel free to get in touch through [support](https://support.hockeyapp.net) where we can share more details about your project setup in private.

Best,
Benjamin

**Comment by simonbromberg** [comment]
I have the same problem. I have setup a new app as you suggested and got the same problem.

I am using Cocoapods 0.39.0.

**Comment by TroubleMakerBen** [comment]
@simonbromberg thanks for letting us know. I just reproduced the issue here with 0.39, too. Seems to be an issue with cocoapods 0.3.9 and Xcode 8.1 GM and not with our SDK.

Let us know in case you run into issues again and have a nice weekend 🖖

**Comment by TroubleMakerBen** [comment]
@Stengo can you try to update to Cocoapods 1.1.1?

**Comment by Stengo** [comment]
@TroubleMakerBen updating to Cocoapods 1.1.1 fixed the issue! Thank you for the quick support :)
