### ISSUE TITLE
Unable to build Hockey SDK via Carthage

### ISSUE THREAD

**Issue by kennymeyers** [bitstadium/HockeySDK-iOS#368]
`.../Carthage/Checkouts/HockeySDK-iOS/Support/HockeySDKTests/BITChannelTests.m:31:27: warning: Null is assigned to a pointer which is expected to have non-null value`

This is not allowing the build of the HockeySDK via Carthage. I'm using the latest version of Carthage and Xcode 8.1.

**Comment by TroubleMakerBen** [comment]
Hi @kennymeyers 

sorry it took so long to reply.

You are right about the warning when building with carthage. We'll fix this in the next version of the SDK for which I can't give you an ETA – I apologize for any inconvenience this causes you.
That said, I just successfully integrated the SDK using Carthage, maybe you can live with the warning for now?

Best,
Benjamin

**Comment by kennymeyers** [comment]
Hey @TroubleMakerBen,

Thanks for the quick response. I was able to build it, but it involved a little bit of timing and commenting out at the right time, and saving right. I can build it, for sure, but it's not great.

Thanks,
Kenny

**Comment by TroubleMakerBen** [comment]
I'm not sure if I'm getting the "commenting out" part. I can just run `carthage update` and it just runs through.
But yes, it should build without warnings, 4.1.3 will have that fixed.

**Comment by TroubleMakerBen** [comment]
This will be fixed in #370 – 4.3.1 will be released in the first half of December.

**Comment by kennymeyers** [comment]
Thanks so much @TroubleMakerBen

**Comment by TroubleMakerBen** [comment]
I just released 4.1.3 of our SDK. =)

**Comment by kennymeyers** [comment]
@TroubleMakerBen Works like a charm.
