### ISSUE TITLE
Xcode analyzer alert

### ISSUE THREAD

**Issue by rwach** [bitstadium/HockeySDK-iOS#371]
The HockeySDK Framework generates some Xcode analyzer alerts like "Null is returned from a method that is expected to return a non-null value" in the Files BITUpdateViewController.m and BITFeedbackListViewController.m

**Comment by TroubleMakerBen** [comment]
Hey @rwach,

thanks for getting in touch. Which version of the SDK are you using? The latest version of our SDK (4.1.2) doesn't have those analyzer warnings. There is one warning that we know related to a unit test and it has been fixed in #370.

**Comment by TroubleMakerBen** [comment]
Hey @rwach,

I'm closing this issue as we haven't heard back from you. Feel free to re-open it at any time.

Best,
Benjamin
