### ISSUE TITLE
Disabling Feedback Manager Does not Remove feedbackObservationMode observer

### ISSUE THREAD

**Issue by jakehoskins-yv** [bitstadium/HockeySDK-iOS#391]

**Comment by lumaxis** [comment]
This is fixed in `develop` by #390

**Comment by TroubleMakerBen** [comment]
FYI: I can't provide an ETA for the next release right now.

**Comment by jakehoskins-yv** [comment]
Okay. I would appreciate it greatly if you could post here when the release goes out.
