### ISSUE TITLE
BITFeedbackMessageAttachment setData Crash iOS9

### ISSUE THREAD

**Issue by bbeversdorf** [bitstadium/HockeySDK-iOS#395]
When `prepareWithItems` is called on an iOS9 device, the application will crash when `setData` is called. This does not crash on iOS10 devices. When `[self->_internalData writeToFile:self.filename atomically:NO];` is set to `[self->_internalData writeToFile:self.filename atomically:YES];` it appears to work as expected (I am not sure of the implications though). 

Attached is a simple test case. 

[HACrash.zip](https://github.com/bitstadium/HockeySDK-iOS/files/772286/HACrash.zip)

**Comment by TroubleMakerBen** [comment]
Hey @bbeversdorf,

Wow, thanks for this! I'm able to repro this thanks to your demo and have the PR ready.
There will be a new release of the SDK, possibly next week.
I'm keeping you updated on this.

Again, thanks a lot!

Benny

**Comment by bbeversdorf** [comment]
@TroubleMakerBen Do you have an idea when the new release of the SDK will be ready? I see that master has been updated.

-Brian

**Comment by TroubleMakerBen** [comment]
This was fixed as of 4.1.4 of the SDK.
