### ISSUE TITLE
startup exception

### ISSUE THREAD

**Issue by amccorma** [bitstadium/HockeySDK-iOS#398]
Looks like there an error in the hockeyapp exception handler on startup.  I am using 4.1.1 and Xamarin.  

The stacktrace is pointing to the hockeyapp library.  I can not reproduce the error.  It seems to happen on certain devices and unsure if the device has already crashed before.

**Application Specific Information:**
*** Terminating app due to uncaught exception 'System.NullReferenceException', reason: 'System.NullReferenceException: Object reference not set to an instance of an object'

Xamarin Exception Stack:
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x10051bee4 + 0x0009b> in <d9a64a30a9e54cff99bd5519750ca6b8#3f818f10c94778d1035e7826de6247d6>:0 
  at psea.ios.Application.Main (System.String[] args) <0x10043b09c + 0x0001b> in <39f820e7eeb24192afee9e82bd43214b#3f818f10c94778d1035e7826de6247d6>:0

Last Exception Backtrace:
0   CoreFoundation                       0x00000001881a91b8 __exceptionPreprocess + 124
1   libobjc.A.dylib                      0x0000000186be055c objc_exception_throw + 52
2   CoreFoundation                       0x00000001881a8e80 -[NSException raise] + 8

**3   mobileios                            0x00000001013e8bb8 **wrapper_managed_to_native_Xamarin_ObjCRuntime_Messaging_void_objc_msgSend_intptr_intptr (<unknown>:1)
4   mobileios                            0x00000001013d8440 HockeySDK_iOSBindings_HockeyApp_iOS_BITHockeyManager_ConvertToNsExceptionAndAbort_object + 280
5   mobileios                            0x00000001013d8574 HockeySDK_iOSBindings_HockeyApp_iOS_BITHockeyManager__StartManagerm__0_object_System_UnhandledExceptionEventArgs + 16****

6   mobileios                            0x000000010083dbf4 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 240
7   mobileios                            0x0000000100325a9c mono_jit_runtime_invoke (mini-runtime.c:2523)
8   mobileios                            0x000000010039463c do_runtime_invoke (object.c:2809)
9   mobileios                            0x00000001003974f4 call_unhandled_exception_delegate (object.c:4362)
10  mobileios                            0x00000001003970d4 mono_unhandled_exception (object.c:4454)
11  mobileios                            0x0000000100316fe0 mono_handle_exception_internal (mini-exceptions.c:1736)
12  mobileios                            0x00000001003161d0 mono_handle_exception (mini-exceptions.c:2027)
13  mobileios                            0x000000010030e0b0 mono_arm_throw_exception (exceptions-arm64.c:388)
14  mobileios                            0x000000010085c0f8 throw_exception + 164

**Comment by TroubleMakerBen** [comment]
Hey @amccorma,

Thank you for getting in touch. I'm sorry to hear you run into an issue with our Xamarin SDK.

PS: I'm closing this issue here as it is related to our Xamarin SDK and [adding the issue in HockeySDK-Xamarin](https://github.com/bitstadium/HockeySDK-Xamarin/issues/69).
