### ISSUE TITLE
Which build for Carthage?

### ISSUE THREAD

**Issue by inPhilly** [bitstadium/HockeySDK-iOS#407]
I see these instructions:

Version without Feedback
carthage build --platform iOS --configuration ReleaseDefault HockeySDK-iOS
Crash-only Version
carthage build --platform iOS --configuration ReleaseCrashOnly HockeySDK-iOS
Crash-only extension
carthage build --platform iOS --configuration ReleaseCrashOnlyExtension HockeySDK-iOS

and it seems that I can only build for one version for the whole project, including app and extensions. But I want my app to use the ReleaseDefault and my extensions to use the  ReleaseCrashOnlyExtension. Can you tell me more specifically how this can be done? Your instructions may be clear to seasoned users of Carthage (or they may not), but I am a relatively new user and it seems like I have to pick only one build and use it for everything. I hope that this is not the case. Thanks!

**Comment by TroubleMakerBen** [comment]
Hi @mommyme,
Thx for getting in touch.

For your use case, I would recommend to use Cocoapods or our binary integration and then use the appropriate framework for each target.
With carthage, you/we cannot customize the output folder and it's not possible to  customize name of dependency to checkout two versions, so there is no way I know of that solves your case. 

Best,
Benny

**Comment by mommyme** [comment]
So basically anyone that has extensions can't use Carthage, right?

**Comment by MatkovIvan** [comment]
Hi @inPhilly!

The Carthage way is one framework per repository. You cannot get several frameworks configurations from one repository via Carthage because one will be replaced by another. I guess binary distribution is better choice for your case.

**Comment by TroubleMakerBen** [comment]
Hey,

I'm closing this issue as it's been around for several months. Please open it again if you still run into this.

Thx!
Benjamin
