### ISSUE TITLE
 Metrics Manager configurable synchronize interval

### ISSUE THREAD

**Issue by joseprl89** [bitstadium/HockeySDK-iOS#410]
Cross-referencing similar issue in Android:

https://github.com/bitstadium/HockeySDK-Android/issues/228

Basically, the interval between batch uploads is not configurable, and defaults to 15 seconds, which can be detrimental to battery usage.

**Comment by TroubleMakerBen** [comment]
Closing this as opening 3 issues makes discussion very hard. Let's use [the Android one](https://github.com/bitstadium/HockeySDK-Android/issues/228) for discussion.
