### ISSUE TITLE
iOS - MetricsManager not working in today's widget extension

### ISSUE THREAD

**Issue by galvanu** [bitstadium/HockeySDK-iOS#415]
Hi,

I'm trying to integrate metricsManager in our today's widget extension but for some reason I can't see the events. All looks good, the SDK doesn't throw any error/warning during initialization process but the events are not sent.

When I'm sending events (with the same code for initialization and trackEvent method) in the app and not in the extension everything works fine.

I also set both Bundle versions string, short and Bundle version to be the same as the app (as described here: https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/hockeyapp-for-ios)

There is any other requirement in order to work with this in app extension?

Thanks!

**Comment by TroubleMakerBen** [comment]
Hey Gal,

Thank you for getting in touch. Our documentation is not very up to date on that part. Actually, Metrics do not work in a today widget extension.
I've added a task to our backlog to add metrics for today widgets but I can't promise an ETA for this.

Best,
Benjamin

**Comment by galvanu** [comment]
Ohhh I got it.
Looks like the documentation has a section about the today widget so I was sure it is working there.
It worth updating/removing this section so people won't try to integrate the SDK in todays widget.

There is anything that I can help with pushing it?
Maybe implement this and create a pull request? Do you need any help with that?

**Comment by TroubleMakerBen** [comment]
Hey @galvanu,

I'm making sure that the docs get updated. Thanks a lot for your input.

Now, talking about a PR, we happily look at and accept PRs. We're hard at work for [Mobile Center](https://www.hockeyapp.net/mobile-center/about/) so I don't know when/if we find some time to look into this myself, so go for it!

Cheers!
Benjamin

**Comment by bmourat** [comment]
Hey @galvanu 
I've created PR for this #449

**Comment by TroubleMakerBen** [comment]
HockeySDK-iOS 5.0.0 contains this feature and was released last week.
=)

**Comment by galvanu** [comment]
Thanks!
