### ISSUE TITLE
Xcode 9 beta issue with LIBCXXABI_NORETURN

### ISSUE THREAD

**Issue by MikeWeller** [bitstadium/HockeySDK-iOS#424]
Building our app with Xcode 9 and the latest iOS 11 beta SDK we are getting errors with the use of `LIBCXXABI_NORETURN`:

```
.../HockeySDK-iOS/Classes/BITCrashCXXExceptionHandler.mm:61:17: error: variable has incomplete type 'void'
extern "C" void LIBCXXABI_NORETURN __cxa_throw(void *exception_object, std::type_info *tinfo, void (*dest)(void *))
                ^
.../HockeySDK-iOS/Classes/BITCrashCXXExceptionHandler.mm:61:35: error: expected ';' after top level declarator
extern "C" void LIBCXXABI_NORETURN __cxa_throw(void *exception_object, std::type_info *tinfo, void (*dest)(void *))
                                  ^
                                  ;
```

We've fixed this temporarily by replacing `LIBCXXABI_NORETURN` with `__attribute__((noreturn))` which I'm assuming is what this used to be anyway. Not sure if `LIBCXXABI_NORETURN` just needs an include (I haven't looked into this too much yet) but perhaps it's better to define your own macro for this anyway, or just use `__attribute__((noreturn))` directly?

**Comment by lumaxis** [comment]
This was fixed by #421 ✌️
