### ISSUE TITLE
Issue with `plcrash_async_thread_state_current symbol` with Xcode 9's New Build System

### ISSUE THREAD

**Issue by MikeWeller** [bitstadium/HockeySDK-iOS#431]
When building HockeySDK with Xcode 9's new build system preview (enabled file Workspace Settings or `xcodebuild -UseNewBuildSystem=YES`), there is an issue with `plcrash_async_thread_state_current` causing the build to fail with a linker error:

```
Ld <snip>/Build/Products/Debug-iphonesimulator/HockeySDK.framework/HockeySDK normal x86_64
...
Undefined symbols for architecture x86_64:
  "_plcrash_async_thread_state_current", referenced from:
      _mach_exception_callback in CrashReporter(PLCrashReporter.o)
      -[PLCrashReporter generateLiveReportWithThread:exception:error:] in CrashReporter(PLCrashReporter.o)
ld: symbol(s) not found for architecture x86_64
```
This seems to be related to differences in the definition of `PLCRASHREPORTER_PREFIX` when PLCrashNamespace.h is included by PLCrashAsyncThread_current.S

Under Xcode 8, `SYM(plcrash_async_thread_state_current)` resolves to `_plcrash_async_thread_state_current`. Under the Xcode 9 new build system, it resolves to `_PL_plcrash_async_thread_state_current` which is not what the linker is looking for later when linking HockeySDK.

After a lot of faffing around I figured out `GCC_PREFIX_HEADER` in the 'current' Xcode build system does not work with .s files, but under the new build system it does. This means PLCrashNamespace.h is now being included twice in PLCrashAsyncThread_current.S - once from the prefix header and once via the `#include`.

Since there is no header guard in PLCrashNamespace.h, if it is included twice strange things can happen... due to the fact that PLCRASHREPORTER_PREFIX is referenced in the first half of the header but then can be defined later on thus affecting a future include of the header in strange ways.

If I stick a header guard on PLCrashNamespace.h this resolves the issue. I can put in a PR for this change if you guys want... but I'm not sure what the status of PLCrashReporter is since the project seemed dead the last time I checked. I guess you guys have your own fork?

edit: I let Apple know this behaviour change affected us in rdar://32873347 - it's not necessarily a bug but they were asking for any feedback/issues at WWDC so I thought I'd let them know.

**Comment by TroubleMakerBen** [comment]
Hi Mike!

Thanks a lot for this very detailed description and the investigation you were doing. That's awesome.
Now, on the PLCrashReporter thing. You are right that we are using a fork which is currently in a private repository. You are also right that it's creators have stopped working on it. That said, I'm working on open sourcing our fork and maybe start making small, incremental changes to it. I'm hoping to open source it by the end of this month and once we're there, I'm happily accepting a pull request for the fix.

I also duped the rdar. =)

Thanks again, for getting in touch and being awesome!

Benny

**Comment by TroubleMakerBen** [comment]
Hey Mike,

Just as an FYI: we're still working on open-sourcing PLCrashReporter, but I can't give you an ETA when exactly that's happening. But it is happening eventually.
That said, we're releasing updates to all of the HA SDKs by the end of July and that includes the Mac SDK, which will fix the issue with the build system, stay tuned.
Best,
Benny

**Comment by MikeWeller** [comment]
Thanks for the update!

**Comment by TroubleMakerBen** [comment]
Hey @MikeWeller,

I'm looking at Xcode compatibility this week. I can compile a demo project just fine using HockeySDK 4.1.6 and Xcode 9-beta.3.
Have you tried compiling your project with beta 3 yet?
I'd appreciate your help a lot.
Benny

**Comment by MikeWeller** [comment]
I still see the issue on beta 3 (building for simulator/x86). However I got an update to the radar this morning asking me to check with beta 4, and indeed it seems to be fixed there.

**Comment by TroubleMakerBen** [comment]
Hey Mike,

This is great news. I'm checking out Beta 4 right now, too.
I'm leaving this issue open until we have Xcode 9 GM in our hands.

Again, I really appreciate any feedback and the time you put into this already.

Best,
Benny

**Comment by TroubleMakerBen** [comment]
I can't repro this in Xcode 9 GM, I'm closing the issue!

Cheers!
Benny
