### ISSUE TITLE
Cannot use Hockey SDK in an Action Extension

### ISSUE THREAD

**Issue by SaqibS** [bitstadium/HockeySDK-iOS#454]
We want to instrument user activity in an extension, but initializing the Hockey SDK, doesn't give any errors - but nor does it work. TrackEvent calls don't get sent.

**Comment by bmourat** [comment]
Hi @SaqibS 

Thanks for getting in touch. There is already a PR #449 that adds support for metrics manager in app extensions. And i double checked that it works in Action extensions. So it's only a matter of this PR being merged. 

Best
Murat

**Comment by SaqibS** [comment]
Any chance of getting this in for 5.0?

**Comment by bmourat** [comment]
I can't really promise anything, but there is a good chance of getting this in 5.0.

**Comment by TroubleMakerBen** [comment]
This is gonna be in 5.0.0!

**Comment by TroubleMakerBen** [comment]
I just released 5.0.0-beta.2 that supports Metrics in extensions. I'm keeping this issue open until 5.0.0 is out as a non-beta.

Thx everyone!

**Comment by TroubleMakerBen** [comment]
We've released 5.0.0! 🎉
