### ISSUE TITLE
Disable code coverage

### ISSUE THREAD

**Issue by cglarsen** [bitstadium/HockeySDK-iOS#467]
Code coverage has to be disabled for Carthage to work with Xcode 9.
Check https://github.com/Carthage/Carthage/issues/2056 and https://github.com/Carthage/Carthage/pull/2057.

On your repo two files need to be changed (sorry for not doing this in a PR) 
 - ```Support/HockeySDK.xcodeproj/xcshareddata/xcschemes/HockeySDK Framework.xcscheme``` line 44
 - ```Support/HockeySDK.xcodeproj/xcshareddata/xcschemes/HockeySDK.xcscheme``` line 45

Change ```codeCoverageEnabled = "YES">``` to ```codeCoverageEnabled = "NO">```

**Comment by TroubleMakerBen** [comment]
Thx @cglarsen for alerting us to this.

**Comment by cglarsen** [comment]
Carthage fixed it on their side in release 0.26. Im closing this one. Thanks for the response.
See https://github.com/Carthage/Carthage/releases/tag/0.26.0

**Comment by TroubleMakerBen** [comment]
@cglarsen thx for notifying me!!!
