### ISSUE TITLE
Event tracking doesn't play nicely with background tasks

### ISSUE THREAD

**Issue by evl5051** [bitstadium/HockeySDK-iOS#474]
We're tracking events in a background task which is kicked off from an actionable notification. In Apple's documentation, they recommend that we call `[UIApplication endBackgroundTask:]` when we're finished with the task. This method call immediately stops the background task.

There are a few situations where we call `[BitMetricsManager trackEventWithName:]` just before we would end the background task, e.g. to record success or failure. Unfortunately, we cannot just call `endBackgroundTask` after `trackEventWithName` returns, since `trackEventWithName` is asynchronous. If we do, there's a race condition where the event may or may not get tracked before the task gets killed.

Of course, we could just introduce an artificial delay of 1s or so before calling `endBackgroundTask`, but that feels hacky to me. Is there any official recommendation on what route to take here?

**Comment by TroubleMakerBen** [comment]
Hey @evl5051,
we have a PR ready for this and it will be part of the next release which is scheduled for late November/early December.

Thx for reporting this and apologies for the inconvenience.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
Let's leave this open until it's released.

**Comment by TroubleMakerBen** [comment]
We just released 5.1.0 which addresses this. I'm closing this issue.
