### ISSUE TITLE
Xcode says: Update to recommended settings

### ISSUE THREAD

**Issue by phoney** [bitstadium/HockeySDK-iOS#490]
I'm using Xcode 9.2 (9C40b) and Hockey SDK 5.1.0 and cocoaPods 1.3.1.

Whenever I pod update Xcode says: 

Target 'HockeySDK-HockeySDKResources' - Adopt "Product Bundle Identifier" build setting Target 'HockeySDK-HockeySDKResources' will have its Info.plists's CFBundleIdentifier key set to "$(PRODUCT_BUNDLE_IDENTIFIER)", and the "PRODUCT_BUNDLE_IDENTIFIER" build setting will be set to "$(PRODUCT_BUNDLE_IDENTIFIER)".

I always "perform changes" but maybe you can fix the project so this doesn't happen.

![screen shot 2017-12-13 at 10 28 50 am](https://user-images.githubusercontent.com/3106038/33946704-78493914-dff0-11e7-82a0-87db327d20d7.png)

**Comment by TroubleMakerBen** [comment]
Hey @phoney !

Thx for raising this issue. We'll include this in 5.1.1 – unfortunately (because of the approaching holidays, etc.) – I can't give you an ETA when this ships.

Thank you for understanding and for using HockeyApp in the first place!

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
Hey @phoney,

this is actually a know issue with cocoapods itself https://github.com/CocoaPods/CocoaPods/issues/7316.

Let's hope they can fix it for 1.4.0.

**Comment by TroubleMakerBen** [comment]
Still around for cocoapods 1.4.0. Let's leave it open!

**Comment by emartinson** [comment]
Hi! Any news here?

**Comment by TroubleMakerBen** [comment]
Hey @emartinson,

looks like this is an ongoing issue with Xcode versions and Cocoapods (see https://github.com/CocoaPods/CocoaPods/issues/7206). We are planning an SDK release around the time of the public iOS 12 release and do some extended testing with the latest Cocoapods version. We'll update this issue accordingly.

**Comment by nickhingston** [comment]
Related to this, Xcode 10 also introduces a number of compiler warnings:

![screenshot 2018-10-10 at 14 26 59](https://user-images.githubusercontent.com/866805/46739566-bba44380-cc98-11e8-8c8e-cf5508065448.png)

![screenshot 2018-10-10 at 14 28 54](https://user-images.githubusercontent.com/866805/46739595-d7a7e500-cc98-11e8-83bb-e7b307fd19f6.png)

**Comment by ElektrojungeAtWork** [comment]
@nickhingston This doesn't look like you are integrating the HockeySDK with Cocoapods, how are you using the HockeySDK and which version?

**Comment by ElektrojungeAtWork** [comment]
I'm leaving this bug open because it mentions the `messaging unqualified id` warnings. There's a PR for fixing that #534.

FYI: I can't provide an ETA for the next SDK release.

**Comment by ElektrojungeAtWork** [comment]
I renamed the issue to reflect better what it is about.

**Comment by nickhingston** [comment]
great, thanks! in answer to your question, no not using cocoapods, just pulling as a subproject

**Comment by ElektrojungeAtWork** [comment]
That's what I thought. Sorry about the warnings, we'll triage this as a bug accordingly!

**Comment by ElektrojungeAtWork** [comment]
Warnings when integrating have been fixed. Unfortunately, I cannot provide an ETA when the next version will be released.

**Comment by mickyzinho** [comment]
Is this still not fixed?

**Comment by elamalani** [comment]
@mickyzinho There is no ETA on releasing HockeySDK with this fix. Our team is working on [App Center](https://appcenter.ms) as the next generation product for HockeyApp and I'd recommend to please look at  [App Center iOS SDK](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios).

**Comment by phoney** [comment]
It's over a year. I think we know the answer is never. In fact I have moved to appcenter, although it has a ton of problems.

**Comment by annakocheshkova** [comment]
@phoney do not hesitate to open new issues. We'll be glad to help you and fix them! You can also start a conversation with us on App Center website using blue chat bubble in the bottom right.

**Comment by elamalani** [comment]
@phoney We are here to make the migration experience very smooth for HockeyApp customers, so please let us know any issues you are facing in App Center. As @annakocheshkova mentioned, you can click on the blue icon on the lower right of the App Center portal and start a conversation with us.
