### ISSUE TITLE
Compiler error when specifying 'CrashOnlyLib' subspec with version 5.1

### ISSUE THREAD

**Issue by drupert-imvu** [bitstadium/HockeySDK-iOS#491]
When updating to the lastest version of HockeySDK I get a compiler error, "Umbrella header for module 'HockeySDK' does not include header 'BITMetricsManager.h'". To make sure it wasn't an issue with updating the pod, I created a sample app and added the HockeySDK to the project. This generated the same error.

Podfile:
platform :ios, '9.0'

target 'TableViewTest' do
    pod 'HockeySDK', '5.1.0', :subspecs => ['CrashOnlyLib']

end

**Comment by TroubleMakerBen** [comment]
Hi @drupert-imvu,

we're working on a 5.1.1 bugfix release. Brace yourself! Sorry for causing any issues.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
5.1.1 is out and fixes this issue!

Apologies for any inconvenience this caused you.

Best,
Benjamin

**Comment by drupert-imvu** [comment]
Thanks! That fixed the issue.
