### ISSUE TITLE
HockeyApp freezes app after background/resume

### ISSUE THREAD

**Issue by phoney** [bitstadium/HockeySDK-iOS#492]
I  updated to v 5.1.0 today and my app now freezes upon background/resume. This didn't happen with 5.0.0 and I've had to go back to that version. All I do is launch the app, tap the home button, tap the app icon in the home screen. The app resumes but the UI is frozen. Clicking the Pause button in Xcode shows the stack trace below. I think this happens every time on various devices. This looks like a deadlock.

The stack trace shows BT code. I don't have an example app  but there's very little BT code in my app. Here it is:

Called from my app delegate at app launch:
            BITHockeyManager.shared().configure(withIdentifier: HockeyAppIdentifier)
            BITHockeyManager.shared().start()
            BITHockeyManager.shared().crashManager.crashManagerStatus = .autoSend
            BITHockeyManager.shared().authenticator.authenticateInstallation()

Called to send custom events:

var timeDiff: TimeInterval = some number of seconds
        BITHockeyManager.shared().metricsManager.trackEvent(withName: eventName, properties: nil, measurements: [timeDifferenceKey : timeDiff as NSNumber])

The stack trace shows 

[BITCHannel timerIsRunning]
[BITChannel registerObservers]

![screen shot 2017-12-13 at 2 46 51 pm](https://user-images.githubusercontent.com/3106038/33962851-e4a1cf06-e020-11e7-83d7-76d829fdd482.png)

**Comment by TroubleMakerBen** [comment]
Hey @phoney,

we just repro'd this. Many apologies from our side. I'll let you know as soon as we have a fix ready.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
There's a new release coming in later today!

**Comment by TroubleMakerBen** [comment]
5.1.1 is out and fixes this issue!
