### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by asowayan** [bitstadium/HockeySDK-iOS#512]
There is a defect in the feedback UI that is preventing us from using it. It is fixed by this commit. When is the next release?

https://github.com/bitstadium/HockeySDK-iOS/commit/ea6b16cdac6414eed1da0bb8dfda580c2db66472

**Comment by elamalani** [comment]
@asowayan We don't have a release planned for iOS SDK. My guesstimate would be in the next 4-5 weeks. I'll keep this issue posted when we decide to release the SDK. Thanks!

**Comment by abbyThompson** [comment]
I've attached a gif of the issue. As you can see, the "Add Image" button is outside of the safe zone and the uploaded image is displayed behind the menu bar making this unusable. Do you have a suggested workaround?

![feedbackvc](https://user-images.githubusercontent.com/36281446/37986159-c42879ce-31c8-11e8-9599-1b89c71332aa.gif)

**Comment by elamalani** [comment]
@abbyThompson @asowayan As a workaround, you can build the SDK and use the binary until we officially release iOS SDK with the fix.

**Comment by abbyThompson** [comment]
Thanks for suggestion. FYI, the button is still behind the home indicator which isn't ideal.

<img width="234" alt="screen shot 2018-03-27 at 4 11 49 pm" src="https://user-images.githubusercontent.com/36281446/37992751-a04b58ca-31da-11e8-8e47-61588fe481af.png">

**Comment by TroubleMakerBen** [comment]
Hi @abbyThompson,

I just merged #513  that fixes this. I'll update this issue as soon as I have an update on the next release date.

Sorry for the wait!

Benjamin

**Comment by TroubleMakerBen** [comment]
I cannot provide an exact ETA at this time but we will have a release available ahead of iOS 12/Xcode 10.

**Comment by ElektrojungeAtWork** [comment]
We just released 5.1.4 of the SDK that includes this fix.
