### ISSUE TITLE
BITUpdateManager not updating automatically

### ISSUE THREAD

**Issue by rafael-chavez** [bitstadium/HockeySDK-iOS#519]
I have done the following in my AppDelegate:
```
        BITHockeyManager.shared().configure(withIdentifier: "myBetaAppIdentifier")
        BITHockeyManager.shared().isUpdateManagerDisabled = false
        BITHockeyManager.shared().start()
```

1. I've installed the beta version via hockeyapp.net
2. Uploaded a newer build number with the same version to the hockeyapp server.
3. Killed the app, and launched.
4. No prompt is shown.

Things to note:
1. UITabBarController is my root controller of the application
2. Using hockeyapp sdk 5.1.2 in swift

Is this a known issue?

**Comment by rafael-chavez** [comment]
`BITHockeyManager.shared().authenticator.authenticateInstallation()` needs to be done after starting the manager.

**Comment by DevJamesFrancis** [comment]
After about an hour I found this... Could you please add this to the documentation for UpdateManager.

The documentation mentions this:

> To use the server side restriction feature, to provide updates only to specific users, you need to setup the BITAuthenticator class. This allows the update request to tell the server which user is using the app on the current device and then let the server decide which updates the device may see.

So I changed to unrestricted downloads but it still didn't work.

Using `BITHockeyManager.shared().updateManager.showUpdateView()` showed that there was indeed an update, so I knew my settings were all correct on the application and website. 

After adding `BITHockeyManager.shared().authenticator.authenticateInstallation()` everything just worked.
