### ISSUE TITLE
Unable to add New iOS Devices to Provisioning Profile

### ISSUE THREAD

**Issue by pulpfree** [bitstadium/HockeySDK-iOS#543]
HockeyApp version: 2.0.22
xCode version: 10.1

After inviting a new test user I find that they are listed in the "Not Listed in Provisioning Profile"
section. After ensuring the user is indeed listed in the Apple Developer portal in the "Devices" section, I attempted to follow the instruction as outlined in: [Adding New iOS Devices to Your Provisioning Profile](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/adding-new-ios-devices-to-your-provisioning-profile). 

The problem I'm having is with step #19: "Select the line for your release configuration and choose the downloaded profile." I don't see this line, see screenshot for my results.

<img width="686" alt="screen shot 2019-01-08 at 10 11 49" src="https://user-images.githubusercontent.com/589916/50839216-ddf83c80-132d-11e9-848c-281d7a46fc9f.png">

I've manually integrated the app as attempting to use the apps installer results int the following:
<img width="683" alt="screen shot 2019-01-08 at 10 13 11" src="https://user-images.githubusercontent.com/589916/50839351-1a2b9d00-132e-11e9-939d-14f388e26128.png">

Any help is appreciated.

**Comment by achocron** [comment]
Instead of searching "code sign" in settings, search "provisioning" and you should see this.
<img width="626" alt="screen shot 2019-01-08 at 11 36 54 am" src="https://user-images.githubusercontent.com/5619585/50854397-c3c45b80-1339-11e9-9059-b4148f0ddca6.png">

Does that help?

**Comment by pulpfree** [comment]
Not clear what to enter here as options are "Automatic" or "other". The other option displays a text box, see attached.

<img width="931" alt="screen shot 2019-01-08 at 15 15 10" src="https://user-images.githubusercontent.com/589916/50856333-6e4b7700-1358-11e9-9747-8710633aed1e.png">

Attempting to build gives me the following error message:
`Showing All Messages
:-1: test has conflicting provisioning settings. test is automatically signed, but provisioning profile Manual has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor. (in target 'test')
`
I'm assuming I need to set "manual signing" but not sure how to go about.

Thanks,
Ron Dyck

**Comment by achocron** [comment]
Sorry, I need to correct myself. I think that you had it right the first time with code sign; it should be the code signing identity for the release configuration.

Did you already drag and drop the downloaded profile into Xcode? (step 16).  I believe it should appear in the drop down that says "iOS Developer"

**Comment by iamclement** [comment]
Anything new on this issue?

**Comment by iamclement** [comment]
Closing this issue as it's been inactive for a while.
