### ISSUE TITLE
Cocoapods only updates to 5.1.2

### ISSUE THREAD

**Issue by philhinco** [bitstadium/HockeySDK-iOS#544]
Hello

I was in the process of updating the CocoaPods in our project.
I have the following in my Podfile:

`pod 'HockeySDK'`

I ran `pod update HockeySDK` to update HockeySDK.

I ran `pod outdated`, which gave me the following output for HockeySDK:

> The following pod updates are available:
> - HockeySDK 5.1.2 -> 5.1.2 (latest version 5.1.4)

Now I was wondering why it wouldn't update to 5.1.4, because I haven't specified a version in my Podfile.

I hope you can help me out with that.

I'm pretty certain that adding a ~> 5.1.4 would probably install 5.1.4, but I'd expect that not having that would also update to the most recent version

**Comment by jaeklim** [comment]
What version of `pod` are you using? It might be caused by CocoaPods cache, you can try to delete all cache and run `pod update HockeySDK`.
This [link](https://gist.github.com/mbinna/4202236) might be helpful to you to delete cache.

**Comment by philhinco** [comment]
@jaelim-ms Things have cleared up. I had iOS 8 set as my minimum deployment target and hadn't noticed that HockeySDK 5.1.3 has upped that target to iOS 9.

After updating the target to iOS 9 in my Podfile the update to 5.1.4 was available.

I'll close this here as the issue has been resolved on my side.

**Comment by jaeklim** [comment]
Ah.. I see. Thanks for getting it back to me.
