### ISSUE TITLE
No crash dialog in main app after crashes via KB extension

### ISSUE THREAD

**Issue by Cloov** [bitstadium/HockeySDK-iOS#549]
What is the process for crashes being submitted when they occur inside an app extension? We tried force-crashing our keyboard extension and then starting up the main app, but haven't received any dialog to ask whether we want to send a report. Is this what should happen? Perhaps we're doing something wrong.

Our setup code in the keyboard is as follows, and fires in viewDidLoad:

BITHockeyManager.shared().configure(withIdentifier: "our ID")
BITHockeyManager.shared().start()

print("Environment: \(BITHockeyManager.shared().appEnvironment)")
// Environment is BITEnvironment

// Then, we force a crash

**Comment by dtrabo** [comment]
Hi @Cloov, thanks for reporting this! Unfortunately, Hockey SDK doesn't display an alert window when a crash reports in extension.

**Comment by Cloov** [comment]
Thanks! So let's say our extension is crashing, but our main app never does. Can we - and should we - programatically enable automatic crash uploads, either in the app or (keyboard) extension, or both, to ensure that we get these extension crash reports?

**Comment by dtrabo** [comment]
Thanks for your patience. The HockeySDK enables crash reporting per default. You don't have to enable this module. Also, it works the same way with extensions. You can find additional information on the next page: https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/hockeyapp-for-ios#3-4-ios-extensions

Let me know if you have any additional questions, please.

**Comment by dtrabo** [comment]
​We're going to close this issue now, but feel free to reply if you have any additional questions or concerns and this conversation will reopen. 

Thanks for using App Center.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
