### ISSUE TITLE
Support Project Catalyst (UIKitForMac)

### ISSUE THREAD

**Issue by jamztang** [bitstadium/HockeySDK-iOS#555]
There were two Errors:

1. When specifying `pod 'HockeySDK', :subspecs => ['CrashOnlyLib']`, `HockeySDK-HockeySDKResources` is missing team identifier.

```
Signing for "HockeySDK-HockeySDKResources" requires a development team. Select a development team in the Signing & Capabilities editor.
```

This could be workaround with appending this to the Podfile

```
post_install do |installer|
	# pods with bundles
	if target.name == 'HockeySDK-HockeySDKResources'
            print "Setting team to `" + target.name + "`"
            target.build_configurations.each do |config|
                config.build_settings['DEVELOPMENT_TEAM'] = 'XXXXXXXX'
            end
	end
end
```

2. HockeySDK.framework seemed to have the wrong architecture

```
/Pods/HockeySDK/HockeySDK-iOS/HockeySDKCrashOnly/HockeySDK.framework/HockeySDK(BITSession.o), building for UIKitForMac, but linking in object file built for iOS Simulator, file '/Volumes/Projects/Baby/Pods/HockeySDK/HockeySDK-iOS/HockeySDKCrashOnly/HockeySDK.framework/HockeySDK' for architecture x86_64
```

This I'm not sure how to work around.

If there're anything I could do to opt-out a Pod when compiling for UIKitForMac would be greatly appreciated as well.

**Comment by dtrabo** [comment]
Hi @jamztang! We have separate sdk for Mac. Please, try this one https://github.com/bitstadium/HockeySDK-Mac.
Let me know if you still have any questions.

**Comment by jamztang** [comment]
Hi @dtrabo, I believe it's going to require changes on how to build the framework, there're some other folks working on this: https://github.com/firebase/firebase-ios-sdk/issues/3144#issuecomment-502150350

But if it's false, I'll still need to be able to incorporate different version of the framework depending on the SDK it's using, are you aware of how to do that?

FYR, I have Xcode project with the Mac target enabled and the Podfile attached.

![Screenshot 2019-07-05 at 8 57 15 am](https://user-images.githubusercontent.com/852375/60691529-f45d0a80-9f02-11e9-860b-69e66a3e9975.png)

Here's my Podfile

```
 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '12.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'Baby' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'HockeySDK', :subspecs => ['CrashOnlyLib'], :inhibit_warnings => true

  target 'BabyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BabyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|

	# pods with bundles
	if target.name == 'HockeySDK-HockeySDKResources'
        print "Setting team to `" + target.name + "`"
        target.build_configurations.each do |config|
            config.build_settings['DEVELOPMENT_TEAM'] = '5UAR78B6YU'
        end
	end
  end

end

```

**Comment by elamalani** [comment]
@jamztang This is a new feature request in HockeySDK. [App Center](https://appcenter.ms) is the next generation solution for HockeyApp and we will sunset HockeyAppp on November 16th, 2019. At this time, we are not adding any new features in HockeyApp SDK.
