### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . 

### ISSUE THREAD

**Issue by csompi** [bitstadium/HockeySDK-iOS#556]
HockeySDK uses UIWebView in BITWebTableViewCell.m.
Soon Apple will reject apps and updates using UIWebView, so it should be changed to WKWebView.

**Comment by MatkovIvan** [comment]
Hey @csompi,

Thanks for bringing our attention to this, we're looking at it.
However, please note that Apple has not announced deadline for this yet. So, this is just a warning at the moment.

**Comment by hamswan** [comment]
We urge you to move to App Center.
